// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/file/audio_file.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   *AudioFile_Description `protobuf:"bytes,1,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFile) Reset() {
	*x = AudioFile{}
	mi := &file_model_file_audio_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFile) ProtoMessage() {}

func (x *AudioFile) ProtoReflect() protoreflect.Message {
	mi := &file_model_file_audio_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFile.ProtoReflect.Descriptor instead.
func (*AudioFile) Descriptor() ([]byte, []int) {
	return file_model_file_audio_file_proto_rawDescGZIP(), []int{0}
}

func (x *AudioFile) GetDescription() *AudioFile_Description {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *AudioFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AudioFile_Description struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Duration      *int32                 `protobuf:"varint,2,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Size          *int32                 `protobuf:"varint,3,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Format        *string                `protobuf:"bytes,4,opt,name=format,proto3,oneof" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFile_Description) Reset() {
	*x = AudioFile_Description{}
	mi := &file_model_file_audio_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFile_Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFile_Description) ProtoMessage() {}

func (x *AudioFile_Description) ProtoReflect() protoreflect.Message {
	mi := &file_model_file_audio_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFile_Description.ProtoReflect.Descriptor instead.
func (*AudioFile_Description) Descriptor() ([]byte, []int) {
	return file_model_file_audio_file_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AudioFile_Description) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AudioFile_Description) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *AudioFile_Description) GetSize() int32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *AudioFile_Description) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

var File_model_file_audio_file_proto protoreflect.FileDescriptor

const file_model_file_audio_file_proto_rawDesc = "" +
	"\n" +
	"\x1bmodel/file/audio_file.proto\x12\x0eim.turms.proto\"\xa5\x02\n" +
	"\tAudioFile\x12L\n" +
	"\vdescription\x18\x01 \x01(\v2%.im.turms.proto.AudioFile.DescriptionH\x00R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fH\x01R\x04data\x88\x01\x01\x1a\x97\x01\n" +
	"\vDescription\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\bduration\x18\x02 \x01(\x05H\x00R\bduration\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x03 \x01(\x05H\x01R\x04size\x88\x01\x01\x12\x1b\n" +
	"\x06format\x18\x04 \x01(\tH\x02R\x06format\x88\x01\x01B\v\n" +
	"\t_durationB\a\n" +
	"\x05_sizeB\t\n" +
	"\a_formatB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_dataBX\n" +
	"3im.turms.server.common.access.client.dto.model.fileP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_file_audio_file_proto_rawDescOnce sync.Once
	file_model_file_audio_file_proto_rawDescData []byte
)

func file_model_file_audio_file_proto_rawDescGZIP() []byte {
	file_model_file_audio_file_proto_rawDescOnce.Do(func() {
		file_model_file_audio_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_file_audio_file_proto_rawDesc), len(file_model_file_audio_file_proto_rawDesc)))
	})
	return file_model_file_audio_file_proto_rawDescData
}

var file_model_file_audio_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_file_audio_file_proto_goTypes = []any{
	(*AudioFile)(nil),             // 0: im.turms.proto.AudioFile
	(*AudioFile_Description)(nil), // 1: im.turms.proto.AudioFile.Description
}
var file_model_file_audio_file_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.AudioFile.description:type_name -> im.turms.proto.AudioFile.Description
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_file_audio_file_proto_init() }
func file_model_file_audio_file_proto_init() {
	if File_model_file_audio_file_proto != nil {
		return
	}
	file_model_file_audio_file_proto_msgTypes[0].OneofWrappers = []any{}
	file_model_file_audio_file_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_file_audio_file_proto_rawDesc), len(file_model_file_audio_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_file_audio_file_proto_goTypes,
		DependencyIndexes: file_model_file_audio_file_proto_depIdxs,
		MessageInfos:      file_model_file_audio_file_proto_msgTypes,
	}.Build()
	File_model_file_audio_file_proto = out.File
	file_model_file_audio_file_proto_goTypes = nil
	file_model_file_audio_file_proto_depIdxs = nil
}
