// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/conversation/conversation_settings_list.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationSettingsList struct {
	state                    protoimpl.MessageState  `protogen:"open.v1"`
	ConversationSettingsList []*ConversationSettings `protobuf:"bytes,1,rep,name=conversation_settings_list,json=conversationSettingsList,proto3" json:"conversation_settings_list,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConversationSettingsList) Reset() {
	*x = ConversationSettingsList{}
	mi := &file_model_conversation_conversation_settings_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSettingsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSettingsList) ProtoMessage() {}

func (x *ConversationSettingsList) ProtoReflect() protoreflect.Message {
	mi := &file_model_conversation_conversation_settings_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSettingsList.ProtoReflect.Descriptor instead.
func (*ConversationSettingsList) Descriptor() ([]byte, []int) {
	return file_model_conversation_conversation_settings_list_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationSettingsList) GetConversationSettingsList() []*ConversationSettings {
	if x != nil {
		return x.ConversationSettingsList
	}
	return nil
}

var File_model_conversation_conversation_settings_list_proto protoreflect.FileDescriptor

const file_model_conversation_conversation_settings_list_proto_rawDesc = "" +
	"\n" +
	"3model/conversation/conversation_settings_list.proto\x12\x0eim.turms.proto\x1a.model/conversation/conversation_settings.proto\"~\n" +
	"\x18ConversationSettingsList\x12b\n" +
	"\x1aconversation_settings_list\x18\x01 \x03(\v2$.im.turms.proto.ConversationSettingsR\x18conversationSettingsListB]\n" +
	";im.turms.server.common.access.client.dto.model.conversationP\x01Z\x1cim.turms/server/pkg/protocolb\x06proto3"

var (
	file_model_conversation_conversation_settings_list_proto_rawDescOnce sync.Once
	file_model_conversation_conversation_settings_list_proto_rawDescData []byte
)

func file_model_conversation_conversation_settings_list_proto_rawDescGZIP() []byte {
	file_model_conversation_conversation_settings_list_proto_rawDescOnce.Do(func() {
		file_model_conversation_conversation_settings_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_conversation_conversation_settings_list_proto_rawDesc), len(file_model_conversation_conversation_settings_list_proto_rawDesc)))
	})
	return file_model_conversation_conversation_settings_list_proto_rawDescData
}

var file_model_conversation_conversation_settings_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_conversation_conversation_settings_list_proto_goTypes = []any{
	(*ConversationSettingsList)(nil), // 0: im.turms.proto.ConversationSettingsList
	(*ConversationSettings)(nil),     // 1: im.turms.proto.ConversationSettings
}
var file_model_conversation_conversation_settings_list_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.ConversationSettingsList.conversation_settings_list:type_name -> im.turms.proto.ConversationSettings
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_conversation_conversation_settings_list_proto_init() }
func file_model_conversation_conversation_settings_list_proto_init() {
	if File_model_conversation_conversation_settings_list_proto != nil {
		return
	}
	file_model_conversation_conversation_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_conversation_conversation_settings_list_proto_rawDesc), len(file_model_conversation_conversation_settings_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_conversation_conversation_settings_list_proto_goTypes,
		DependencyIndexes: file_model_conversation_conversation_settings_list_proto_depIdxs,
		MessageInfos:      file_model_conversation_conversation_settings_list_proto_msgTypes,
	}.Build()
	File_model_conversation_conversation_settings_list_proto = out.File
	file_model_conversation_conversation_settings_list_proto_goTypes = nil
	file_model_conversation_conversation_settings_list_proto_depIdxs = nil
}
