// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/conversation/conversations.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conversations struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PrivateConversations []*PrivateConversation `protobuf:"bytes,1,rep,name=private_conversations,json=privateConversations,proto3" json:"private_conversations,omitempty"`
	GroupConversations   []*GroupConversation   `protobuf:"bytes,2,rep,name=group_conversations,json=groupConversations,proto3" json:"group_conversations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Conversations) Reset() {
	*x = Conversations{}
	mi := &file_model_conversation_conversations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversations) ProtoMessage() {}

func (x *Conversations) ProtoReflect() protoreflect.Message {
	mi := &file_model_conversation_conversations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversations.ProtoReflect.Descriptor instead.
func (*Conversations) Descriptor() ([]byte, []int) {
	return file_model_conversation_conversations_proto_rawDescGZIP(), []int{0}
}

func (x *Conversations) GetPrivateConversations() []*PrivateConversation {
	if x != nil {
		return x.PrivateConversations
	}
	return nil
}

func (x *Conversations) GetGroupConversations() []*GroupConversation {
	if x != nil {
		return x.GroupConversations
	}
	return nil
}

var File_model_conversation_conversations_proto protoreflect.FileDescriptor

const file_model_conversation_conversations_proto_rawDesc = "" +
	"\n" +
	"&model/conversation/conversations.proto\x12\x0eim.turms.proto\x1a-model/conversation/private_conversation.proto\x1a+model/conversation/group_conversation.proto\"\xbd\x01\n" +
	"\rConversations\x12X\n" +
	"\x15private_conversations\x18\x01 \x03(\v2#.im.turms.proto.PrivateConversationR\x14privateConversations\x12R\n" +
	"\x13group_conversations\x18\x02 \x03(\v2!.im.turms.proto.GroupConversationR\x12groupConversationsB`\n" +
	";im.turms.server.common.access.client.dto.model.conversationP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_conversation_conversations_proto_rawDescOnce sync.Once
	file_model_conversation_conversations_proto_rawDescData []byte
)

func file_model_conversation_conversations_proto_rawDescGZIP() []byte {
	file_model_conversation_conversations_proto_rawDescOnce.Do(func() {
		file_model_conversation_conversations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_conversation_conversations_proto_rawDesc), len(file_model_conversation_conversations_proto_rawDesc)))
	})
	return file_model_conversation_conversations_proto_rawDescData
}

var file_model_conversation_conversations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_conversation_conversations_proto_goTypes = []any{
	(*Conversations)(nil),       // 0: im.turms.proto.Conversations
	(*PrivateConversation)(nil), // 1: im.turms.proto.PrivateConversation
	(*GroupConversation)(nil),   // 2: im.turms.proto.GroupConversation
}
var file_model_conversation_conversations_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.Conversations.private_conversations:type_name -> im.turms.proto.PrivateConversation
	2, // 1: im.turms.proto.Conversations.group_conversations:type_name -> im.turms.proto.GroupConversation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_conversation_conversations_proto_init() }
func file_model_conversation_conversations_proto_init() {
	if File_model_conversation_conversations_proto != nil {
		return
	}
	file_model_conversation_private_conversation_proto_init()
	file_model_conversation_group_conversation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_conversation_conversations_proto_rawDesc), len(file_model_conversation_conversations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_conversation_conversations_proto_goTypes,
		DependencyIndexes: file_model_conversation_conversations_proto_depIdxs,
		MessageInfos:      file_model_conversation_conversations_proto_msgTypes,
	}.Build()
	File_model_conversation_conversations_proto = out.File
	file_model_conversation_conversations_proto_goTypes = nil
	file_model_conversation_conversations_proto_depIdxs = nil
}
