// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/message/create_message_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMessageRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MessageId *int64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	// is_system_message can only be true if the user is an administrator,
	// or turms server will return an error
	IsSystemMessage *bool    `protobuf:"varint,2,opt,name=is_system_message,json=isSystemMessage,proto3,oneof" json:"is_system_message,omitempty"`
	GroupId         *int64   `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	RecipientId     *int64   `protobuf:"varint,4,opt,name=recipient_id,json=recipientId,proto3,oneof" json:"recipient_id,omitempty"`
	DeliveryDate    *int64   `protobuf:"varint,5,opt,name=delivery_date,json=deliveryDate,proto3,oneof" json:"delivery_date,omitempty"`
	Text            *string  `protobuf:"bytes,6,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Records         [][]byte `protobuf:"bytes,7,rep,name=records,proto3" json:"records,omitempty"`
	BurnAfter       *int32   `protobuf:"varint,8,opt,name=burn_after,json=burnAfter,proto3,oneof" json:"burn_after,omitempty"`
	PreMessageId    *int64   `protobuf:"varint,9,opt,name=pre_message_id,json=preMessageId,proto3,oneof" json:"pre_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_request_message_create_message_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_message_create_message_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_request_message_create_message_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMessageRequest) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *CreateMessageRequest) GetIsSystemMessage() bool {
	if x != nil && x.IsSystemMessage != nil {
		return *x.IsSystemMessage
	}
	return false
}

func (x *CreateMessageRequest) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *CreateMessageRequest) GetRecipientId() int64 {
	if x != nil && x.RecipientId != nil {
		return *x.RecipientId
	}
	return 0
}

func (x *CreateMessageRequest) GetDeliveryDate() int64 {
	if x != nil && x.DeliveryDate != nil {
		return *x.DeliveryDate
	}
	return 0
}

func (x *CreateMessageRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *CreateMessageRequest) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *CreateMessageRequest) GetBurnAfter() int32 {
	if x != nil && x.BurnAfter != nil {
		return *x.BurnAfter
	}
	return 0
}

func (x *CreateMessageRequest) GetPreMessageId() int64 {
	if x != nil && x.PreMessageId != nil {
		return *x.PreMessageId
	}
	return 0
}

var File_request_message_create_message_request_proto protoreflect.FileDescriptor

const file_request_message_create_message_request_proto_rawDesc = "" +
	"\n" +
	",request/message/create_message_request.proto\x12\x0eim.turms.proto\"\xdf\x03\n" +
	"\x14CreateMessageRequest\x12\"\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03H\x00R\tmessageId\x88\x01\x01\x12/\n" +
	"\x11is_system_message\x18\x02 \x01(\bH\x01R\x0fisSystemMessage\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\x03H\x02R\agroupId\x88\x01\x01\x12&\n" +
	"\frecipient_id\x18\x04 \x01(\x03H\x03R\vrecipientId\x88\x01\x01\x12(\n" +
	"\rdelivery_date\x18\x05 \x01(\x03H\x04R\fdeliveryDate\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x06 \x01(\tH\x05R\x04text\x88\x01\x01\x12\x18\n" +
	"\arecords\x18\a \x03(\fR\arecords\x12\"\n" +
	"\n" +
	"burn_after\x18\b \x01(\x05H\x06R\tburnAfter\x88\x01\x01\x12)\n" +
	"\x0epre_message_id\x18\t \x01(\x03H\aR\fpreMessageId\x88\x01\x01B\r\n" +
	"\v_message_idB\x14\n" +
	"\x12_is_system_messageB\v\n" +
	"\t_group_idB\x0f\n" +
	"\r_recipient_idB\x10\n" +
	"\x0e_delivery_dateB\a\n" +
	"\x05_textB\r\n" +
	"\v_burn_afterB\x11\n" +
	"\x0f_pre_message_idB]\n" +
	"8im.turms.server.common.access.client.dto.request.messageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_message_create_message_request_proto_rawDescOnce sync.Once
	file_request_message_create_message_request_proto_rawDescData []byte
)

func file_request_message_create_message_request_proto_rawDescGZIP() []byte {
	file_request_message_create_message_request_proto_rawDescOnce.Do(func() {
		file_request_message_create_message_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_message_create_message_request_proto_rawDesc), len(file_request_message_create_message_request_proto_rawDesc)))
	})
	return file_request_message_create_message_request_proto_rawDescData
}

var file_request_message_create_message_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_message_create_message_request_proto_goTypes = []any{
	(*CreateMessageRequest)(nil), // 0: im.turms.proto.CreateMessageRequest
}
var file_request_message_create_message_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_message_create_message_request_proto_init() }
func file_request_message_create_message_request_proto_init() {
	if File_request_message_create_message_request_proto != nil {
		return
	}
	file_request_message_create_message_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_message_create_message_request_proto_rawDesc), len(file_request_message_create_message_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_message_create_message_request_proto_goTypes,
		DependencyIndexes: file_request_message_create_message_request_proto_depIdxs,
		MessageInfos:      file_request_message_create_message_request_proto_msgTypes,
	}.Build()
	File_request_message_create_message_request_proto = out.File
	file_request_message_create_message_request_proto_goTypes = nil
	file_request_message_create_message_request_proto_depIdxs = nil
}
