// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/member/create_group_members_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds       []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Role          *GroupMemberRole       `protobuf:"varint,4,opt,name=role,proto3,enum=im.turms.proto.GroupMemberRole,oneof" json:"role,omitempty"`
	MuteEndDate   *int64                 `protobuf:"varint,5,opt,name=mute_end_date,json=muteEndDate,proto3,oneof" json:"mute_end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupMembersRequest) Reset() {
	*x = CreateGroupMembersRequest{}
	mi := &file_request_group_member_create_group_members_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupMembersRequest) ProtoMessage() {}

func (x *CreateGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_member_create_group_members_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_request_group_member_create_group_members_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupMembersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupMembersRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *CreateGroupMembersRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateGroupMembersRequest) GetRole() GroupMemberRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return GroupMemberRole_OWNER
}

func (x *CreateGroupMembersRequest) GetMuteEndDate() int64 {
	if x != nil && x.MuteEndDate != nil {
		return *x.MuteEndDate
	}
	return 0
}

var File_request_group_member_create_group_members_request_proto protoreflect.FileDescriptor

const file_request_group_member_create_group_members_request_proto_rawDesc = "" +
	"\n" +
	"7request/group/member/create_group_members_request.proto\x12\x0eim.turms.proto\x1a constant/group_member_role.proto\"\xf1\x01\n" +
	"\x19CreateGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x128\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1f.im.turms.proto.GroupMemberRoleH\x01R\x04role\x88\x01\x01\x12'\n" +
	"\rmute_end_date\x18\x05 \x01(\x03H\x02R\vmuteEndDate\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_roleB\x10\n" +
	"\x0e_mute_end_dateBb\n" +
	"=im.turms.server.common.access.client.dto.request.group.memberP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_member_create_group_members_request_proto_rawDescOnce sync.Once
	file_request_group_member_create_group_members_request_proto_rawDescData []byte
)

func file_request_group_member_create_group_members_request_proto_rawDescGZIP() []byte {
	file_request_group_member_create_group_members_request_proto_rawDescOnce.Do(func() {
		file_request_group_member_create_group_members_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_member_create_group_members_request_proto_rawDesc), len(file_request_group_member_create_group_members_request_proto_rawDesc)))
	})
	return file_request_group_member_create_group_members_request_proto_rawDescData
}

var file_request_group_member_create_group_members_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_member_create_group_members_request_proto_goTypes = []any{
	(*CreateGroupMembersRequest)(nil), // 0: im.turms.proto.CreateGroupMembersRequest
	(GroupMemberRole)(0),              // 1: im.turms.proto.GroupMemberRole
}
var file_request_group_member_create_group_members_request_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.CreateGroupMembersRequest.role:type_name -> im.turms.proto.GroupMemberRole
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_group_member_create_group_members_request_proto_init() }
func file_request_group_member_create_group_members_request_proto_init() {
	if File_request_group_member_create_group_members_request_proto != nil {
		return
	}
	file_constant_group_member_role_proto_init()
	file_request_group_member_create_group_members_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_member_create_group_members_request_proto_rawDesc), len(file_request_group_member_create_group_members_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_member_create_group_members_request_proto_goTypes,
		DependencyIndexes: file_request_group_member_create_group_members_request_proto_depIdxs,
		MessageInfos:      file_request_group_member_create_group_members_request_proto_msgTypes,
	}.Build()
	File_request_group_member_create_group_members_request_proto = out.File
	file_request_group_member_create_group_members_request_proto_goTypes = nil
	file_request_group_member_create_group_members_request_proto_depIdxs = nil
}
