// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/relationship/create_friend_request_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFriendRequestRequest) Reset() {
	*x = CreateFriendRequestRequest{}
	mi := &file_request_user_relationship_create_friend_request_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFriendRequestRequest) ProtoMessage() {}

func (x *CreateFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_relationship_create_friend_request_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*CreateFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_request_user_relationship_create_friend_request_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFriendRequestRequest) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *CreateFriendRequestRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_request_user_relationship_create_friend_request_request_proto protoreflect.FileDescriptor

const file_request_user_relationship_create_friend_request_request_proto_rawDesc = "" +
	"\n" +
	"=request/user/relationship/create_friend_request_request.proto\x12\x0eim.turms.proto\"Y\n" +
	"\x1aCreateFriendRequestRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentBg\n" +
	"Bim.turms.server.common.access.client.dto.request.user.relationshipP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_relationship_create_friend_request_request_proto_rawDescOnce sync.Once
	file_request_user_relationship_create_friend_request_request_proto_rawDescData []byte
)

func file_request_user_relationship_create_friend_request_request_proto_rawDescGZIP() []byte {
	file_request_user_relationship_create_friend_request_request_proto_rawDescOnce.Do(func() {
		file_request_user_relationship_create_friend_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_relationship_create_friend_request_request_proto_rawDesc), len(file_request_user_relationship_create_friend_request_request_proto_rawDesc)))
	})
	return file_request_user_relationship_create_friend_request_request_proto_rawDescData
}

var file_request_user_relationship_create_friend_request_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_user_relationship_create_friend_request_request_proto_goTypes = []any{
	(*CreateFriendRequestRequest)(nil), // 0: im.turms.proto.CreateFriendRequestRequest
}
var file_request_user_relationship_create_friend_request_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_user_relationship_create_friend_request_request_proto_init() }
func file_request_user_relationship_create_friend_request_request_proto_init() {
	if File_request_user_relationship_create_friend_request_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_relationship_create_friend_request_request_proto_rawDesc), len(file_request_user_relationship_create_friend_request_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_relationship_create_friend_request_request_proto_goTypes,
		DependencyIndexes: file_request_user_relationship_create_friend_request_request_proto_depIdxs,
		MessageInfos:      file_request_user_relationship_create_friend_request_request_proto_msgTypes,
	}.Build()
	File_request_user_relationship_create_friend_request_request_proto = out.File
	file_request_user_relationship_create_friend_request_request_proto_goTypes = nil
	file_request_user_relationship_create_friend_request_request_proto_depIdxs = nil
}
