// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/create_group_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Intro         *string                `protobuf:"bytes,2,opt,name=intro,proto3,oneof" json:"intro,omitempty"`
	Announcement  *string                `protobuf:"bytes,3,opt,name=announcement,proto3,oneof" json:"announcement,omitempty"`
	MinScore      *int32                 `protobuf:"varint,4,opt,name=min_score,json=minScore,proto3,oneof" json:"min_score,omitempty"`
	TypeId        *int64                 `protobuf:"varint,5,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id,omitempty"`
	MuteEndDate   *int64                 `protobuf:"varint,6,opt,name=mute_end_date,json=muteEndDate,proto3,oneof" json:"mute_end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_request_group_create_group_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_create_group_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_request_group_create_group_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetIntro() string {
	if x != nil && x.Intro != nil {
		return *x.Intro
	}
	return ""
}

func (x *CreateGroupRequest) GetAnnouncement() string {
	if x != nil && x.Announcement != nil {
		return *x.Announcement
	}
	return ""
}

func (x *CreateGroupRequest) GetMinScore() int32 {
	if x != nil && x.MinScore != nil {
		return *x.MinScore
	}
	return 0
}

func (x *CreateGroupRequest) GetTypeId() int64 {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return 0
}

func (x *CreateGroupRequest) GetMuteEndDate() int64 {
	if x != nil && x.MuteEndDate != nil {
		return *x.MuteEndDate
	}
	return 0
}

var File_request_group_create_group_request_proto protoreflect.FileDescriptor

const file_request_group_create_group_request_proto_rawDesc = "" +
	"\n" +
	"(request/group/create_group_request.proto\x12\x0eim.turms.proto\"\x9c\x02\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05intro\x18\x02 \x01(\tH\x00R\x05intro\x88\x01\x01\x12'\n" +
	"\fannouncement\x18\x03 \x01(\tH\x01R\fannouncement\x88\x01\x01\x12 \n" +
	"\tmin_score\x18\x04 \x01(\x05H\x02R\bminScore\x88\x01\x01\x12\x1c\n" +
	"\atype_id\x18\x05 \x01(\x03H\x03R\x06typeId\x88\x01\x01\x12'\n" +
	"\rmute_end_date\x18\x06 \x01(\x03H\x04R\vmuteEndDate\x88\x01\x01B\b\n" +
	"\x06_introB\x0f\n" +
	"\r_announcementB\f\n" +
	"\n" +
	"_min_scoreB\n" +
	"\n" +
	"\b_type_idB\x10\n" +
	"\x0e_mute_end_dateB[\n" +
	"6im.turms.server.common.access.client.dto.request.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_create_group_request_proto_rawDescOnce sync.Once
	file_request_group_create_group_request_proto_rawDescData []byte
)

func file_request_group_create_group_request_proto_rawDescGZIP() []byte {
	file_request_group_create_group_request_proto_rawDescOnce.Do(func() {
		file_request_group_create_group_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_create_group_request_proto_rawDesc), len(file_request_group_create_group_request_proto_rawDesc)))
	})
	return file_request_group_create_group_request_proto_rawDescData
}

var file_request_group_create_group_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_create_group_request_proto_goTypes = []any{
	(*CreateGroupRequest)(nil), // 0: im.turms.proto.CreateGroupRequest
}
var file_request_group_create_group_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_group_create_group_request_proto_init() }
func file_request_group_create_group_request_proto_init() {
	if File_request_group_create_group_request_proto != nil {
		return
	}
	file_request_group_create_group_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_create_group_request_proto_rawDesc), len(file_request_group_create_group_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_create_group_request_proto_goTypes,
		DependencyIndexes: file_request_group_create_group_request_proto_depIdxs,
		MessageInfos:      file_request_group_create_group_request_proto_msgTypes,
	}.Build()
	File_request_group_create_group_request_proto = out.File
	file_request_group_create_group_request_proto_goTypes = nil
	file_request_group_create_group_request_proto_depIdxs = nil
}
