// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/relationship/delete_relationship_group_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteRelationshipGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupIndex       int32                  `protobuf:"varint,1,opt,name=group_index,json=groupIndex,proto3" json:"group_index,omitempty"`
	TargetGroupIndex *int32                 `protobuf:"varint,2,opt,name=target_group_index,json=targetGroupIndex,proto3,oneof" json:"target_group_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRelationshipGroupRequest) Reset() {
	*x = DeleteRelationshipGroupRequest{}
	mi := &file_request_user_relationship_delete_relationship_group_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationshipGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationshipGroupRequest) ProtoMessage() {}

func (x *DeleteRelationshipGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_relationship_delete_relationship_group_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationshipGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationshipGroupRequest) Descriptor() ([]byte, []int) {
	return file_request_user_relationship_delete_relationship_group_request_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteRelationshipGroupRequest) GetGroupIndex() int32 {
	if x != nil {
		return x.GroupIndex
	}
	return 0
}

func (x *DeleteRelationshipGroupRequest) GetTargetGroupIndex() int32 {
	if x != nil && x.TargetGroupIndex != nil {
		return *x.TargetGroupIndex
	}
	return 0
}

var File_request_user_relationship_delete_relationship_group_request_proto protoreflect.FileDescriptor

const file_request_user_relationship_delete_relationship_group_request_proto_rawDesc = "" +
	"\n" +
	"Arequest/user/relationship/delete_relationship_group_request.proto\x12\x0eim.turms.proto\"\x8b\x01\n" +
	"\x1eDeleteRelationshipGroupRequest\x12\x1f\n" +
	"\vgroup_index\x18\x01 \x01(\x05R\n" +
	"groupIndex\x121\n" +
	"\x12target_group_index\x18\x02 \x01(\x05H\x00R\x10targetGroupIndex\x88\x01\x01B\x15\n" +
	"\x13_target_group_indexBg\n" +
	"Bim.turms.server.common.access.client.dto.request.user.relationshipP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_relationship_delete_relationship_group_request_proto_rawDescOnce sync.Once
	file_request_user_relationship_delete_relationship_group_request_proto_rawDescData []byte
)

func file_request_user_relationship_delete_relationship_group_request_proto_rawDescGZIP() []byte {
	file_request_user_relationship_delete_relationship_group_request_proto_rawDescOnce.Do(func() {
		file_request_user_relationship_delete_relationship_group_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_relationship_delete_relationship_group_request_proto_rawDesc), len(file_request_user_relationship_delete_relationship_group_request_proto_rawDesc)))
	})
	return file_request_user_relationship_delete_relationship_group_request_proto_rawDescData
}

var file_request_user_relationship_delete_relationship_group_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_user_relationship_delete_relationship_group_request_proto_goTypes = []any{
	(*DeleteRelationshipGroupRequest)(nil), // 0: im.turms.proto.DeleteRelationshipGroupRequest
}
var file_request_user_relationship_delete_relationship_group_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_user_relationship_delete_relationship_group_request_proto_init() }
func file_request_user_relationship_delete_relationship_group_request_proto_init() {
	if File_request_user_relationship_delete_relationship_group_request_proto != nil {
		return
	}
	file_request_user_relationship_delete_relationship_group_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_relationship_delete_relationship_group_request_proto_rawDesc), len(file_request_user_relationship_delete_relationship_group_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_relationship_delete_relationship_group_request_proto_goTypes,
		DependencyIndexes: file_request_user_relationship_delete_relationship_group_request_proto_depIdxs,
		MessageInfos:      file_request_user_relationship_delete_relationship_group_request_proto_msgTypes,
	}.Build()
	File_request_user_relationship_delete_relationship_group_request_proto = out.File
	file_request_user_relationship_delete_relationship_group_request_proto_goTypes = nil
	file_request_user_relationship_delete_relationship_group_request_proto_depIdxs = nil
}
