// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/conversation/delete_conversation_settings_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteConversationSettingsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserIds          []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	GroupIds         []int64                `protobuf:"varint,2,rep,packed,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	Names            []string               `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	CustomAttributes []*Value               `protobuf:"bytes,15,rep,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteConversationSettingsRequest) Reset() {
	*x = DeleteConversationSettingsRequest{}
	mi := &file_request_conversation_delete_conversation_settings_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationSettingsRequest) ProtoMessage() {}

func (x *DeleteConversationSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_conversation_delete_conversation_settings_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationSettingsRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationSettingsRequest) Descriptor() ([]byte, []int) {
	return file_request_conversation_delete_conversation_settings_request_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteConversationSettingsRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *DeleteConversationSettingsRequest) GetGroupIds() []int64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

func (x *DeleteConversationSettingsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *DeleteConversationSettingsRequest) GetCustomAttributes() []*Value {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

var File_request_conversation_delete_conversation_settings_request_proto protoreflect.FileDescriptor

const file_request_conversation_delete_conversation_settings_request_proto_rawDesc = "" +
	"\n" +
	"?request/conversation/delete_conversation_settings_request.proto\x12\x0eim.turms.proto\x1a\x18model/common/value.proto\"\xb5\x01\n" +
	"!DeleteConversationSettingsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x1b\n" +
	"\tgroup_ids\x18\x02 \x03(\x03R\bgroupIds\x12\x14\n" +
	"\x05names\x18\x03 \x03(\tR\x05names\x12B\n" +
	"\x11custom_attributes\x18\x0f \x03(\v2\x15.im.turms.proto.ValueR\x10customAttributesB_\n" +
	"=im.turms.server.common.access.client.dto.request.conversationP\x01Z\x1cim.turms/server/pkg/protocolb\x06proto3"

var (
	file_request_conversation_delete_conversation_settings_request_proto_rawDescOnce sync.Once
	file_request_conversation_delete_conversation_settings_request_proto_rawDescData []byte
)

func file_request_conversation_delete_conversation_settings_request_proto_rawDescGZIP() []byte {
	file_request_conversation_delete_conversation_settings_request_proto_rawDescOnce.Do(func() {
		file_request_conversation_delete_conversation_settings_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_conversation_delete_conversation_settings_request_proto_rawDesc), len(file_request_conversation_delete_conversation_settings_request_proto_rawDesc)))
	})
	return file_request_conversation_delete_conversation_settings_request_proto_rawDescData
}

var file_request_conversation_delete_conversation_settings_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_conversation_delete_conversation_settings_request_proto_goTypes = []any{
	(*DeleteConversationSettingsRequest)(nil), // 0: im.turms.proto.DeleteConversationSettingsRequest
	(*Value)(nil), // 1: im.turms.proto.Value
}
var file_request_conversation_delete_conversation_settings_request_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.DeleteConversationSettingsRequest.custom_attributes:type_name -> im.turms.proto.Value
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_conversation_delete_conversation_settings_request_proto_init() }
func file_request_conversation_delete_conversation_settings_request_proto_init() {
	if File_request_conversation_delete_conversation_settings_request_proto != nil {
		return
	}
	file_model_common_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_conversation_delete_conversation_settings_request_proto_rawDesc), len(file_request_conversation_delete_conversation_settings_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_conversation_delete_conversation_settings_request_proto_goTypes,
		DependencyIndexes: file_request_conversation_delete_conversation_settings_request_proto_depIdxs,
		MessageInfos:      file_request_conversation_delete_conversation_settings_request_proto_msgTypes,
	}.Build()
	File_request_conversation_delete_conversation_settings_request_proto = out.File
	file_request_conversation_delete_conversation_settings_request_proto_goTypes = nil
	file_request_conversation_delete_conversation_settings_request_proto_depIdxs = nil
}
