// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/blocklist/delete_group_blocked_user_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteGroupBlockedUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupBlockedUserRequest) Reset() {
	*x = DeleteGroupBlockedUserRequest{}
	mi := &file_request_group_blocklist_delete_group_blocked_user_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupBlockedUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupBlockedUserRequest) ProtoMessage() {}

func (x *DeleteGroupBlockedUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_blocklist_delete_group_blocked_user_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupBlockedUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupBlockedUserRequest) Descriptor() ([]byte, []int) {
	return file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteGroupBlockedUserRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DeleteGroupBlockedUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_request_group_blocklist_delete_group_blocked_user_request_proto protoreflect.FileDescriptor

const file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDesc = "" +
	"\n" +
	"?request/group/blocklist/delete_group_blocked_user_request.proto\x12\x0eim.turms.proto\"S\n" +
	"\x1dDeleteGroupBlockedUserRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userIdBe\n" +
	"@im.turms.server.common.access.client.dto.request.group.blocklistP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescOnce sync.Once
	file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescData []byte
)

func file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescGZIP() []byte {
	file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescOnce.Do(func() {
		file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDesc), len(file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDesc)))
	})
	return file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDescData
}

var file_request_group_blocklist_delete_group_blocked_user_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_blocklist_delete_group_blocked_user_request_proto_goTypes = []any{
	(*DeleteGroupBlockedUserRequest)(nil), // 0: im.turms.proto.DeleteGroupBlockedUserRequest
}
var file_request_group_blocklist_delete_group_blocked_user_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_group_blocklist_delete_group_blocked_user_request_proto_init() }
func file_request_group_blocklist_delete_group_blocked_user_request_proto_init() {
	if File_request_group_blocklist_delete_group_blocked_user_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDesc), len(file_request_group_blocklist_delete_group_blocked_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_blocklist_delete_group_blocked_user_request_proto_goTypes,
		DependencyIndexes: file_request_group_blocklist_delete_group_blocked_user_request_proto_depIdxs,
		MessageInfos:      file_request_group_blocklist_delete_group_blocked_user_request_proto_msgTypes,
	}.Build()
	File_request_group_blocklist_delete_group_blocked_user_request_proto = out.File
	file_request_group_blocklist_delete_group_blocked_user_request_proto_goTypes = nil
	file_request_group_blocklist_delete_group_blocked_user_request_proto_depIdxs = nil
}
