// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/group/group_member.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMember struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupId          *int64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	UserId           *int64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Name             *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Role             *GroupMemberRole       `protobuf:"varint,4,opt,name=role,proto3,enum=im.turms.proto.GroupMemberRole,oneof" json:"role,omitempty"`
	JoinDate         *int64                 `protobuf:"varint,5,opt,name=join_date,json=joinDate,proto3,oneof" json:"join_date,omitempty"`
	MuteEndDate      *int64                 `protobuf:"varint,6,opt,name=mute_end_date,json=muteEndDate,proto3,oneof" json:"mute_end_date,omitempty"`
	UserStatus       *UserStatus            `protobuf:"varint,7,opt,name=user_status,json=userStatus,proto3,enum=im.turms.proto.UserStatus,oneof" json:"user_status,omitempty"`
	UsingDeviceTypes []DeviceType           `protobuf:"varint,8,rep,packed,name=using_device_types,json=usingDeviceTypes,proto3,enum=im.turms.proto.DeviceType" json:"using_device_types,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_model_group_group_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_model_group_group_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_model_group_group_member_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMember) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GroupMember) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GroupMember) GetRole() GroupMemberRole {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return GroupMemberRole_OWNER
}

func (x *GroupMember) GetJoinDate() int64 {
	if x != nil && x.JoinDate != nil {
		return *x.JoinDate
	}
	return 0
}

func (x *GroupMember) GetMuteEndDate() int64 {
	if x != nil && x.MuteEndDate != nil {
		return *x.MuteEndDate
	}
	return 0
}

func (x *GroupMember) GetUserStatus() UserStatus {
	if x != nil && x.UserStatus != nil {
		return *x.UserStatus
	}
	return UserStatus_AVAILABLE
}

func (x *GroupMember) GetUsingDeviceTypes() []DeviceType {
	if x != nil {
		return x.UsingDeviceTypes
	}
	return nil
}

var File_model_group_group_member_proto protoreflect.FileDescriptor

const file_model_group_group_member_proto_rawDesc = "" +
	"\n" +
	"\x1emodel/group/group_member.proto\x12\x0eim.turms.proto\x1a constant/group_member_role.proto\x1a\x1aconstant/user_status.proto\x1a\x1aconstant/device_type.proto\"\xd0\x03\n" +
	"\vGroupMember\x12\x1e\n" +
	"\bgroup_id\x18\x01 \x01(\x03H\x00R\agroupId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x128\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1f.im.turms.proto.GroupMemberRoleH\x03R\x04role\x88\x01\x01\x12 \n" +
	"\tjoin_date\x18\x05 \x01(\x03H\x04R\bjoinDate\x88\x01\x01\x12'\n" +
	"\rmute_end_date\x18\x06 \x01(\x03H\x05R\vmuteEndDate\x88\x01\x01\x12@\n" +
	"\vuser_status\x18\a \x01(\x0e2\x1a.im.turms.proto.UserStatusH\x06R\n" +
	"userStatus\x88\x01\x01\x12H\n" +
	"\x12using_device_types\x18\b \x03(\x0e2\x1a.im.turms.proto.DeviceTypeR\x10usingDeviceTypesB\v\n" +
	"\t_group_idB\n" +
	"\n" +
	"\b_user_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_roleB\f\n" +
	"\n" +
	"_join_dateB\x10\n" +
	"\x0e_mute_end_dateB\x0e\n" +
	"\f_user_statusBY\n" +
	"4im.turms.server.common.access.client.dto.model.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_group_group_member_proto_rawDescOnce sync.Once
	file_model_group_group_member_proto_rawDescData []byte
)

func file_model_group_group_member_proto_rawDescGZIP() []byte {
	file_model_group_group_member_proto_rawDescOnce.Do(func() {
		file_model_group_group_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_group_group_member_proto_rawDesc), len(file_model_group_group_member_proto_rawDesc)))
	})
	return file_model_group_group_member_proto_rawDescData
}

var file_model_group_group_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_group_group_member_proto_goTypes = []any{
	(*GroupMember)(nil),  // 0: im.turms.proto.GroupMember
	(GroupMemberRole)(0), // 1: im.turms.proto.GroupMemberRole
	(UserStatus)(0),      // 2: im.turms.proto.UserStatus
	(DeviceType)(0),      // 3: im.turms.proto.DeviceType
}
var file_model_group_group_member_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.GroupMember.role:type_name -> im.turms.proto.GroupMemberRole
	2, // 1: im.turms.proto.GroupMember.user_status:type_name -> im.turms.proto.UserStatus
	3, // 2: im.turms.proto.GroupMember.using_device_types:type_name -> im.turms.proto.DeviceType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_group_group_member_proto_init() }
func file_model_group_group_member_proto_init() {
	if File_model_group_group_member_proto != nil {
		return
	}
	file_constant_group_member_role_proto_init()
	file_constant_user_status_proto_init()
	file_constant_device_type_proto_init()
	file_model_group_group_member_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_group_group_member_proto_rawDesc), len(file_model_group_group_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_group_group_member_proto_goTypes,
		DependencyIndexes: file_model_group_group_member_proto_depIdxs,
		MessageInfos:      file_model_group_group_member_proto_msgTypes,
	}.Build()
	File_model_group_group_member_proto = out.File
	file_model_group_group_member_proto_goTypes = nil
	file_model_group_group_member_proto_depIdxs = nil
}
