// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/group/group.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	TypeId          *int64                 `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id,omitempty"`
	CreatorId       *int64                 `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3,oneof" json:"creator_id,omitempty"`
	OwnerId         *int64                 `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3,oneof" json:"owner_id,omitempty"`
	Name            *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Intro           *string                `protobuf:"bytes,6,opt,name=intro,proto3,oneof" json:"intro,omitempty"`
	Announcement    *string                `protobuf:"bytes,7,opt,name=announcement,proto3,oneof" json:"announcement,omitempty"`
	CreationDate    *int64                 `protobuf:"varint,8,opt,name=creation_date,json=creationDate,proto3,oneof" json:"creation_date,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,9,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	MuteEndDate     *int64                 `protobuf:"varint,10,opt,name=mute_end_date,json=muteEndDate,proto3,oneof" json:"mute_end_date,omitempty"`
	Active          *bool                  `protobuf:"varint,11,opt,name=active,proto3,oneof" json:"active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_model_group_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_model_group_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_model_group_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Group) GetTypeId() int64 {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return 0
}

func (x *Group) GetCreatorId() int64 {
	if x != nil && x.CreatorId != nil {
		return *x.CreatorId
	}
	return 0
}

func (x *Group) GetOwnerId() int64 {
	if x != nil && x.OwnerId != nil {
		return *x.OwnerId
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Group) GetIntro() string {
	if x != nil && x.Intro != nil {
		return *x.Intro
	}
	return ""
}

func (x *Group) GetAnnouncement() string {
	if x != nil && x.Announcement != nil {
		return *x.Announcement
	}
	return ""
}

func (x *Group) GetCreationDate() int64 {
	if x != nil && x.CreationDate != nil {
		return *x.CreationDate
	}
	return 0
}

func (x *Group) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

func (x *Group) GetMuteEndDate() int64 {
	if x != nil && x.MuteEndDate != nil {
		return *x.MuteEndDate
	}
	return 0
}

func (x *Group) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

var File_model_group_group_proto protoreflect.FileDescriptor

const file_model_group_group_proto_rawDesc = "" +
	"\n" +
	"\x17model/group/group.proto\x12\x0eim.turms.proto\"\x94\x04\n" +
	"\x05Group\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x1c\n" +
	"\atype_id\x18\x02 \x01(\x03H\x01R\x06typeId\x88\x01\x01\x12\"\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\x03H\x02R\tcreatorId\x88\x01\x01\x12\x1e\n" +
	"\bowner_id\x18\x04 \x01(\x03H\x03R\aownerId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x04R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05intro\x18\x06 \x01(\tH\x05R\x05intro\x88\x01\x01\x12'\n" +
	"\fannouncement\x18\a \x01(\tH\x06R\fannouncement\x88\x01\x01\x12(\n" +
	"\rcreation_date\x18\b \x01(\x03H\aR\fcreationDate\x88\x01\x01\x12/\n" +
	"\x11last_updated_date\x18\t \x01(\x03H\bR\x0flastUpdatedDate\x88\x01\x01\x12'\n" +
	"\rmute_end_date\x18\n" +
	" \x01(\x03H\tR\vmuteEndDate\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\v \x01(\bH\n" +
	"R\x06active\x88\x01\x01B\x05\n" +
	"\x03_idB\n" +
	"\n" +
	"\b_type_idB\r\n" +
	"\v_creator_idB\v\n" +
	"\t_owner_idB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_introB\x0f\n" +
	"\r_announcementB\x10\n" +
	"\x0e_creation_dateB\x14\n" +
	"\x12_last_updated_dateB\x10\n" +
	"\x0e_mute_end_dateB\t\n" +
	"\a_activeBY\n" +
	"4im.turms.server.common.access.client.dto.model.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_group_group_proto_rawDescOnce sync.Once
	file_model_group_group_proto_rawDescData []byte
)

func file_model_group_group_proto_rawDescGZIP() []byte {
	file_model_group_group_proto_rawDescOnce.Do(func() {
		file_model_group_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_group_group_proto_rawDesc), len(file_model_group_group_proto_rawDesc)))
	})
	return file_model_group_group_proto_rawDescData
}

var file_model_group_group_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_group_group_proto_goTypes = []any{
	(*Group)(nil), // 0: im.turms.proto.Group
}
var file_model_group_group_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_group_group_proto_init() }
func file_model_group_group_proto_init() {
	if File_model_group_group_proto != nil {
		return
	}
	file_model_group_group_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_group_group_proto_rawDesc), len(file_model_group_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_group_group_proto_goTypes,
		DependencyIndexes: file_model_group_group_proto_depIdxs,
		MessageInfos:      file_model_group_group_proto_msgTypes,
	}.Build()
	File_model_group_group_proto = out.File
	file_model_group_group_proto_goTypes = nil
	file_model_group_group_proto_depIdxs = nil
}
