// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/conversation/group_conversation.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupConversation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GroupId            int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	MemberIdToReadDate map[int64]int64        `protobuf:"bytes,2,rep,name=member_id_to_read_date,json=memberIdToReadDate,proto3" json:"member_id_to_read_date,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupConversation) Reset() {
	*x = GroupConversation{}
	mi := &file_model_conversation_group_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupConversation) ProtoMessage() {}

func (x *GroupConversation) ProtoReflect() protoreflect.Message {
	mi := &file_model_conversation_group_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupConversation.ProtoReflect.Descriptor instead.
func (*GroupConversation) Descriptor() ([]byte, []int) {
	return file_model_conversation_group_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *GroupConversation) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupConversation) GetMemberIdToReadDate() map[int64]int64 {
	if x != nil {
		return x.MemberIdToReadDate
	}
	return nil
}

var File_model_conversation_group_conversation_proto protoreflect.FileDescriptor

const file_model_conversation_group_conversation_proto_rawDesc = "" +
	"\n" +
	"+model/conversation/group_conversation.proto\x12\x0eim.turms.proto\"\xe4\x01\n" +
	"\x11GroupConversation\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12m\n" +
	"\x16member_id_to_read_date\x18\x02 \x03(\v29.im.turms.proto.GroupConversation.MemberIdToReadDateEntryR\x12memberIdToReadDate\x1aE\n" +
	"\x17MemberIdToReadDateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B`\n" +
	";im.turms.server.common.access.client.dto.model.conversationP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_conversation_group_conversation_proto_rawDescOnce sync.Once
	file_model_conversation_group_conversation_proto_rawDescData []byte
)

func file_model_conversation_group_conversation_proto_rawDescGZIP() []byte {
	file_model_conversation_group_conversation_proto_rawDescOnce.Do(func() {
		file_model_conversation_group_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_conversation_group_conversation_proto_rawDesc), len(file_model_conversation_group_conversation_proto_rawDesc)))
	})
	return file_model_conversation_group_conversation_proto_rawDescData
}

var file_model_conversation_group_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_conversation_group_conversation_proto_goTypes = []any{
	(*GroupConversation)(nil), // 0: im.turms.proto.GroupConversation
	nil,                       // 1: im.turms.proto.GroupConversation.MemberIdToReadDateEntry
}
var file_model_conversation_group_conversation_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.GroupConversation.member_id_to_read_date:type_name -> im.turms.proto.GroupConversation.MemberIdToReadDateEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_conversation_group_conversation_proto_init() }
func file_model_conversation_group_conversation_proto_init() {
	if File_model_conversation_group_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_conversation_group_conversation_proto_rawDesc), len(file_model_conversation_group_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_conversation_group_conversation_proto_goTypes,
		DependencyIndexes: file_model_conversation_group_conversation_proto_depIdxs,
		MessageInfos:      file_model_conversation_group_conversation_proto_msgTypes,
	}.Build()
	File_model_conversation_group_conversation_proto = out.File
	file_model_conversation_group_conversation_proto_goTypes = nil
	file_model_conversation_group_conversation_proto_depIdxs = nil
}
