// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/group/group_members_with_version.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupMembersWithVersion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupMembers    []*GroupMember         `protobuf:"bytes,1,rep,name=group_members,json=groupMembers,proto3" json:"group_members,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,2,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupMembersWithVersion) Reset() {
	*x = GroupMembersWithVersion{}
	mi := &file_model_group_group_members_with_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersWithVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersWithVersion) ProtoMessage() {}

func (x *GroupMembersWithVersion) ProtoReflect() protoreflect.Message {
	mi := &file_model_group_group_members_with_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersWithVersion.ProtoReflect.Descriptor instead.
func (*GroupMembersWithVersion) Descriptor() ([]byte, []int) {
	return file_model_group_group_members_with_version_proto_rawDescGZIP(), []int{0}
}

func (x *GroupMembersWithVersion) GetGroupMembers() []*GroupMember {
	if x != nil {
		return x.GroupMembers
	}
	return nil
}

func (x *GroupMembersWithVersion) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

var File_model_group_group_members_with_version_proto protoreflect.FileDescriptor

const file_model_group_group_members_with_version_proto_rawDesc = "" +
	"\n" +
	",model/group/group_members_with_version.proto\x12\x0eim.turms.proto\x1a\x1emodel/group/group_member.proto\"\xa2\x01\n" +
	"\x17GroupMembersWithVersion\x12@\n" +
	"\rgroup_members\x18\x01 \x03(\v2\x1b.im.turms.proto.GroupMemberR\fgroupMembers\x12/\n" +
	"\x11last_updated_date\x18\x02 \x01(\x03H\x00R\x0flastUpdatedDate\x88\x01\x01B\x14\n" +
	"\x12_last_updated_dateBY\n" +
	"4im.turms.server.common.access.client.dto.model.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_group_group_members_with_version_proto_rawDescOnce sync.Once
	file_model_group_group_members_with_version_proto_rawDescData []byte
)

func file_model_group_group_members_with_version_proto_rawDescGZIP() []byte {
	file_model_group_group_members_with_version_proto_rawDescOnce.Do(func() {
		file_model_group_group_members_with_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_group_group_members_with_version_proto_rawDesc), len(file_model_group_group_members_with_version_proto_rawDesc)))
	})
	return file_model_group_group_members_with_version_proto_rawDescData
}

var file_model_group_group_members_with_version_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_group_group_members_with_version_proto_goTypes = []any{
	(*GroupMembersWithVersion)(nil), // 0: im.turms.proto.GroupMembersWithVersion
	(*GroupMember)(nil),             // 1: im.turms.proto.GroupMember
}
var file_model_group_group_members_with_version_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.GroupMembersWithVersion.group_members:type_name -> im.turms.proto.GroupMember
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_group_group_members_with_version_proto_init() }
func file_model_group_group_members_with_version_proto_init() {
	if File_model_group_group_members_with_version_proto != nil {
		return
	}
	file_model_group_group_member_proto_init()
	file_model_group_group_members_with_version_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_group_group_members_with_version_proto_rawDesc), len(file_model_group_group_members_with_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_group_group_members_with_version_proto_goTypes,
		DependencyIndexes: file_model_group_group_members_with_version_proto_depIdxs,
		MessageInfos:      file_model_group_group_members_with_version_proto_msgTypes,
	}.Build()
	File_model_group_group_members_with_version_proto = out.File
	file_model_group_group_members_with_version_proto_goTypes = nil
	file_model_group_group_members_with_version_proto_depIdxs = nil
}
