// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/group/group_join_question.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupJoinQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	GroupId       *int64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	Question      *string                `protobuf:"bytes,3,opt,name=question,proto3,oneof" json:"question,omitempty"`
	Answers       []string               `protobuf:"bytes,4,rep,name=answers,proto3" json:"answers,omitempty"`
	Score         *int32                 `protobuf:"varint,5,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoinQuestion) Reset() {
	*x = GroupJoinQuestion{}
	mi := &file_model_group_group_join_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinQuestion) ProtoMessage() {}

func (x *GroupJoinQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_model_group_group_join_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinQuestion.ProtoReflect.Descriptor instead.
func (*GroupJoinQuestion) Descriptor() ([]byte, []int) {
	return file_model_group_group_join_question_proto_rawDescGZIP(), []int{0}
}

func (x *GroupJoinQuestion) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GroupJoinQuestion) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *GroupJoinQuestion) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

func (x *GroupJoinQuestion) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *GroupJoinQuestion) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

var File_model_group_group_join_question_proto protoreflect.FileDescriptor

const file_model_group_group_join_question_proto_rawDesc = "" +
	"\n" +
	"%model/group/group_join_question.proto\x12\x0eim.turms.proto\"\xc9\x01\n" +
	"\x11GroupJoinQuestion\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x02 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12\x1f\n" +
	"\bquestion\x18\x03 \x01(\tH\x02R\bquestion\x88\x01\x01\x12\x18\n" +
	"\aanswers\x18\x04 \x03(\tR\aanswers\x12\x19\n" +
	"\x05score\x18\x05 \x01(\x05H\x03R\x05score\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_group_idB\v\n" +
	"\t_questionB\b\n" +
	"\x06_scoreBY\n" +
	"4im.turms.server.common.access.client.dto.model.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_group_group_join_question_proto_rawDescOnce sync.Once
	file_model_group_group_join_question_proto_rawDescData []byte
)

func file_model_group_group_join_question_proto_rawDescGZIP() []byte {
	file_model_group_group_join_question_proto_rawDescOnce.Do(func() {
		file_model_group_group_join_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_group_group_join_question_proto_rawDesc), len(file_model_group_group_join_question_proto_rawDesc)))
	})
	return file_model_group_group_join_question_proto_rawDescData
}

var file_model_group_group_join_question_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_group_group_join_question_proto_goTypes = []any{
	(*GroupJoinQuestion)(nil), // 0: im.turms.proto.GroupJoinQuestion
}
var file_model_group_group_join_question_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_group_group_join_question_proto_init() }
func file_model_group_group_join_question_proto_init() {
	if File_model_group_group_join_question_proto != nil {
		return
	}
	file_model_group_group_join_question_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_group_group_join_question_proto_rawDesc), len(file_model_group_group_join_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_group_group_join_question_proto_goTypes,
		DependencyIndexes: file_model_group_group_join_question_proto_depIdxs,
		MessageInfos:      file_model_group_group_join_question_proto_msgTypes,
	}.Build()
	File_model_group_group_join_question_proto = out.File
	file_model_group_group_join_question_proto_goTypes = nil
	file_model_group_group_join_question_proto_depIdxs = nil
}
