// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/group/group_invitation.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupInvitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CreationDate   *int64                 `protobuf:"varint,2,opt,name=creation_date,json=creationDate,proto3,oneof" json:"creation_date,omitempty"`
	Content        *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Status         *RequestStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=im.turms.proto.RequestStatus,oneof" json:"status,omitempty"`
	ExpirationDate *int64                 `protobuf:"varint,5,opt,name=expiration_date,json=expirationDate,proto3,oneof" json:"expiration_date,omitempty"`
	GroupId        *int64                 `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	InviterId      *int64                 `protobuf:"varint,7,opt,name=inviter_id,json=inviterId,proto3,oneof" json:"inviter_id,omitempty"`
	InviteeId      *int64                 `protobuf:"varint,8,opt,name=invitee_id,json=inviteeId,proto3,oneof" json:"invitee_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupInvitation) Reset() {
	*x = GroupInvitation{}
	mi := &file_model_group_group_invitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInvitation) ProtoMessage() {}

func (x *GroupInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_model_group_group_invitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInvitation.ProtoReflect.Descriptor instead.
func (*GroupInvitation) Descriptor() ([]byte, []int) {
	return file_model_group_group_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *GroupInvitation) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *GroupInvitation) GetCreationDate() int64 {
	if x != nil && x.CreationDate != nil {
		return *x.CreationDate
	}
	return 0
}

func (x *GroupInvitation) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *GroupInvitation) GetStatus() RequestStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return RequestStatus_PENDING
}

func (x *GroupInvitation) GetExpirationDate() int64 {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return 0
}

func (x *GroupInvitation) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *GroupInvitation) GetInviterId() int64 {
	if x != nil && x.InviterId != nil {
		return *x.InviterId
	}
	return 0
}

func (x *GroupInvitation) GetInviteeId() int64 {
	if x != nil && x.InviteeId != nil {
		return *x.InviteeId
	}
	return 0
}

var File_model_group_group_invitation_proto protoreflect.FileDescriptor

const file_model_group_group_invitation_proto_rawDesc = "" +
	"\n" +
	"\"model/group/group_invitation.proto\x12\x0eim.turms.proto\x1a\x1dconstant/request_status.proto\"\xb0\x03\n" +
	"\x0fGroupInvitation\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12(\n" +
	"\rcreation_date\x18\x02 \x01(\x03H\x01R\fcreationDate\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x02R\acontent\x88\x01\x01\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.im.turms.proto.RequestStatusH\x03R\x06status\x88\x01\x01\x12,\n" +
	"\x0fexpiration_date\x18\x05 \x01(\x03H\x04R\x0eexpirationDate\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x06 \x01(\x03H\x05R\agroupId\x88\x01\x01\x12\"\n" +
	"\n" +
	"inviter_id\x18\a \x01(\x03H\x06R\tinviterId\x88\x01\x01\x12\"\n" +
	"\n" +
	"invitee_id\x18\b \x01(\x03H\aR\tinviteeId\x88\x01\x01B\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_creation_dateB\n" +
	"\n" +
	"\b_contentB\t\n" +
	"\a_statusB\x12\n" +
	"\x10_expiration_dateB\v\n" +
	"\t_group_idB\r\n" +
	"\v_inviter_idB\r\n" +
	"\v_invitee_idBY\n" +
	"4im.turms.server.common.access.client.dto.model.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_group_group_invitation_proto_rawDescOnce sync.Once
	file_model_group_group_invitation_proto_rawDescData []byte
)

func file_model_group_group_invitation_proto_rawDescGZIP() []byte {
	file_model_group_group_invitation_proto_rawDescOnce.Do(func() {
		file_model_group_group_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_group_group_invitation_proto_rawDesc), len(file_model_group_group_invitation_proto_rawDesc)))
	})
	return file_model_group_group_invitation_proto_rawDescData
}

var file_model_group_group_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_group_group_invitation_proto_goTypes = []any{
	(*GroupInvitation)(nil), // 0: im.turms.proto.GroupInvitation
	(RequestStatus)(0),      // 1: im.turms.proto.RequestStatus
}
var file_model_group_group_invitation_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.GroupInvitation.status:type_name -> im.turms.proto.RequestStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_group_group_invitation_proto_init() }
func file_model_group_group_invitation_proto_init() {
	if File_model_group_group_invitation_proto != nil {
		return
	}
	file_constant_request_status_proto_init()
	file_model_group_group_invitation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_group_group_invitation_proto_rawDesc), len(file_model_group_group_invitation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_group_group_invitation_proto_goTypes,
		DependencyIndexes: file_model_group_group_invitation_proto_depIdxs,
		MessageInfos:      file_model_group_group_invitation_proto_msgTypes,
	}.Build()
	File_model_group_group_invitation_proto = out.File
	file_model_group_group_invitation_proto_goTypes = nil
	file_model_group_group_invitation_proto_depIdxs = nil
}
