// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/file/image_file.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   *ImageFile_Description `protobuf:"bytes,1,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageFile) Reset() {
	*x = ImageFile{}
	mi := &file_model_file_image_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFile) ProtoMessage() {}

func (x *ImageFile) ProtoReflect() protoreflect.Message {
	mi := &file_model_file_image_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFile.ProtoReflect.Descriptor instead.
func (*ImageFile) Descriptor() ([]byte, []int) {
	return file_model_file_image_file_proto_rawDescGZIP(), []int{0}
}

func (x *ImageFile) GetDescription() *ImageFile_Description {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *ImageFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImageFile_Description struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Original      *bool                  `protobuf:"varint,2,opt,name=original,proto3,oneof" json:"original,omitempty"`
	ImageSize     *int32                 `protobuf:"varint,3,opt,name=image_size,json=imageSize,proto3,oneof" json:"image_size,omitempty"`
	FileSize      *int32                 `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3,oneof" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageFile_Description) Reset() {
	*x = ImageFile_Description{}
	mi := &file_model_file_image_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFile_Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFile_Description) ProtoMessage() {}

func (x *ImageFile_Description) ProtoReflect() protoreflect.Message {
	mi := &file_model_file_image_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFile_Description.ProtoReflect.Descriptor instead.
func (*ImageFile_Description) Descriptor() ([]byte, []int) {
	return file_model_file_image_file_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ImageFile_Description) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageFile_Description) GetOriginal() bool {
	if x != nil && x.Original != nil {
		return *x.Original
	}
	return false
}

func (x *ImageFile_Description) GetImageSize() int32 {
	if x != nil && x.ImageSize != nil {
		return *x.ImageSize
	}
	return 0
}

func (x *ImageFile_Description) GetFileSize() int32 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

var File_model_file_image_file_proto protoreflect.FileDescriptor

const file_model_file_image_file_proto_rawDesc = "" +
	"\n" +
	"\x1bmodel/file/image_file.proto\x12\x0eim.turms.proto\"\xbe\x02\n" +
	"\tImageFile\x12L\n" +
	"\vdescription\x18\x01 \x01(\v2%.im.turms.proto.ImageFile.DescriptionH\x00R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04data\x18\x02 \x01(\fH\x01R\x04data\x88\x01\x01\x1a\xb0\x01\n" +
	"\vDescription\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\boriginal\x18\x02 \x01(\bH\x00R\boriginal\x88\x01\x01\x12\"\n" +
	"\n" +
	"image_size\x18\x03 \x01(\x05H\x01R\timageSize\x88\x01\x01\x12 \n" +
	"\tfile_size\x18\x04 \x01(\x05H\x02R\bfileSize\x88\x01\x01B\v\n" +
	"\t_originalB\r\n" +
	"\v_image_sizeB\f\n" +
	"\n" +
	"_file_sizeB\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_dataBX\n" +
	"3im.turms.server.common.access.client.dto.model.fileP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_file_image_file_proto_rawDescOnce sync.Once
	file_model_file_image_file_proto_rawDescData []byte
)

func file_model_file_image_file_proto_rawDescGZIP() []byte {
	file_model_file_image_file_proto_rawDescOnce.Do(func() {
		file_model_file_image_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_file_image_file_proto_rawDesc), len(file_model_file_image_file_proto_rawDesc)))
	})
	return file_model_file_image_file_proto_rawDescData
}

var file_model_file_image_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_file_image_file_proto_goTypes = []any{
	(*ImageFile)(nil),             // 0: im.turms.proto.ImageFile
	(*ImageFile_Description)(nil), // 1: im.turms.proto.ImageFile.Description
}
var file_model_file_image_file_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.ImageFile.description:type_name -> im.turms.proto.ImageFile.Description
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_file_image_file_proto_init() }
func file_model_file_image_file_proto_init() {
	if File_model_file_image_file_proto != nil {
		return
	}
	file_model_file_image_file_proto_msgTypes[0].OneofWrappers = []any{}
	file_model_file_image_file_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_file_image_file_proto_rawDesc), len(file_model_file_image_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_file_image_file_proto_goTypes,
		DependencyIndexes: file_model_file_image_file_proto_depIdxs,
		MessageInfos:      file_model_file_image_file_proto_msgTypes,
	}.Build()
	File_model_file_image_file_proto = out.File
	file_model_file_image_file_proto_goTypes = nil
	file_model_file_image_file_proto_depIdxs = nil
}
