// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/common/longs_with_version.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongsWithVersion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Longs           []int64                `protobuf:"varint,1,rep,packed,name=longs,proto3" json:"longs,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,2,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LongsWithVersion) Reset() {
	*x = LongsWithVersion{}
	mi := &file_model_common_longs_with_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongsWithVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongsWithVersion) ProtoMessage() {}

func (x *LongsWithVersion) ProtoReflect() protoreflect.Message {
	mi := &file_model_common_longs_with_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongsWithVersion.ProtoReflect.Descriptor instead.
func (*LongsWithVersion) Descriptor() ([]byte, []int) {
	return file_model_common_longs_with_version_proto_rawDescGZIP(), []int{0}
}

func (x *LongsWithVersion) GetLongs() []int64 {
	if x != nil {
		return x.Longs
	}
	return nil
}

func (x *LongsWithVersion) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

var File_model_common_longs_with_version_proto protoreflect.FileDescriptor

const file_model_common_longs_with_version_proto_rawDesc = "" +
	"\n" +
	"%model/common/longs_with_version.proto\x12\x0eim.turms.proto\"o\n" +
	"\x10LongsWithVersion\x12\x14\n" +
	"\x05longs\x18\x01 \x03(\x03R\x05longs\x12/\n" +
	"\x11last_updated_date\x18\x02 \x01(\x03H\x00R\x0flastUpdatedDate\x88\x01\x01B\x14\n" +
	"\x12_last_updated_dateBZ\n" +
	"5im.turms.server.common.access.client.dto.model.commonP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_common_longs_with_version_proto_rawDescOnce sync.Once
	file_model_common_longs_with_version_proto_rawDescData []byte
)

func file_model_common_longs_with_version_proto_rawDescGZIP() []byte {
	file_model_common_longs_with_version_proto_rawDescOnce.Do(func() {
		file_model_common_longs_with_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_common_longs_with_version_proto_rawDesc), len(file_model_common_longs_with_version_proto_rawDesc)))
	})
	return file_model_common_longs_with_version_proto_rawDescData
}

var file_model_common_longs_with_version_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_common_longs_with_version_proto_goTypes = []any{
	(*LongsWithVersion)(nil), // 0: im.turms.proto.LongsWithVersion
}
var file_model_common_longs_with_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_common_longs_with_version_proto_init() }
func file_model_common_longs_with_version_proto_init() {
	if File_model_common_longs_with_version_proto != nil {
		return
	}
	file_model_common_longs_with_version_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_common_longs_with_version_proto_rawDesc), len(file_model_common_longs_with_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_common_longs_with_version_proto_goTypes,
		DependencyIndexes: file_model_common_longs_with_version_proto_depIdxs,
		MessageInfos:      file_model_common_longs_with_version_proto_msgTypes,
	}.Build()
	File_model_common_longs_with_version_proto = out.File
	file_model_common_longs_with_version_proto_goTypes = nil
	file_model_common_longs_with_version_proto_depIdxs = nil
}
