// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/conference/meeting.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meeting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        *int64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	GroupId       *int64                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	AccessToken   *string                `protobuf:"bytes,5,opt,name=access_token,json=accessToken,proto3,oneof" json:"access_token,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Intro         *string                `protobuf:"bytes,7,opt,name=intro,proto3,oneof" json:"intro,omitempty"`
	Password      *string                `protobuf:"bytes,8,opt,name=password,proto3,oneof" json:"password,omitempty"`
	StartDate     int64                  `protobuf:"varint,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *int64                 `protobuf:"varint,10,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	CancelDate    *int64                 `protobuf:"varint,11,opt,name=cancel_date,json=cancelDate,proto3,oneof" json:"cancel_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meeting) Reset() {
	*x = Meeting{}
	mi := &file_model_conference_meeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meeting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meeting) ProtoMessage() {}

func (x *Meeting) ProtoReflect() protoreflect.Message {
	mi := &file_model_conference_meeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meeting.ProtoReflect.Descriptor instead.
func (*Meeting) Descriptor() ([]byte, []int) {
	return file_model_conference_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *Meeting) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Meeting) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *Meeting) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *Meeting) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Meeting) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *Meeting) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Meeting) GetIntro() string {
	if x != nil && x.Intro != nil {
		return *x.Intro
	}
	return ""
}

func (x *Meeting) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Meeting) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *Meeting) GetEndDate() int64 {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return 0
}

func (x *Meeting) GetCancelDate() int64 {
	if x != nil && x.CancelDate != nil {
		return *x.CancelDate
	}
	return 0
}

var File_model_conference_meeting_proto protoreflect.FileDescriptor

const file_model_conference_meeting_proto_rawDesc = "" +
	"\n" +
	"\x1emodel/conference/meeting.proto\x12\x0eim.turms.proto\"\xbf\x03\n" +
	"\aMeeting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x03 \x01(\x03H\x01R\agroupId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\x03R\tcreatorId\x12&\n" +
	"\faccess_token\x18\x05 \x01(\tH\x02R\vaccessToken\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x03R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05intro\x18\a \x01(\tH\x04R\x05intro\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\b \x01(\tH\x05R\bpassword\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"start_date\x18\t \x01(\x03R\tstartDate\x12\x1e\n" +
	"\bend_date\x18\n" +
	" \x01(\x03H\x06R\aendDate\x88\x01\x01\x12$\n" +
	"\vcancel_date\x18\v \x01(\x03H\aR\n" +
	"cancelDate\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\v\n" +
	"\t_group_idB\x0f\n" +
	"\r_access_tokenB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_introB\v\n" +
	"\t_passwordB\v\n" +
	"\t_end_dateB\x0e\n" +
	"\f_cancel_dateB[\n" +
	"9im.turms.server.common.access.client.dto.model.conferenceP\x01Z\x1cim.turms/server/pkg/protocolb\x06proto3"

var (
	file_model_conference_meeting_proto_rawDescOnce sync.Once
	file_model_conference_meeting_proto_rawDescData []byte
)

func file_model_conference_meeting_proto_rawDescGZIP() []byte {
	file_model_conference_meeting_proto_rawDescOnce.Do(func() {
		file_model_conference_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_conference_meeting_proto_rawDesc), len(file_model_conference_meeting_proto_rawDesc)))
	})
	return file_model_conference_meeting_proto_rawDescData
}

var file_model_conference_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_conference_meeting_proto_goTypes = []any{
	(*Meeting)(nil), // 0: im.turms.proto.Meeting
}
var file_model_conference_meeting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_conference_meeting_proto_init() }
func file_model_conference_meeting_proto_init() {
	if File_model_conference_meeting_proto != nil {
		return
	}
	file_model_conference_meeting_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_conference_meeting_proto_rawDesc), len(file_model_conference_meeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_conference_meeting_proto_goTypes,
		DependencyIndexes: file_model_conference_meeting_proto_depIdxs,
		MessageInfos:      file_model_conference_meeting_proto_msgTypes,
	}.Build()
	File_model_conference_meeting_proto = out.File
	file_model_conference_meeting_proto_goTypes = nil
	file_model_conference_meeting_proto_depIdxs = nil
}
