// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/message/messages_with_total.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessagesWithTotal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	IsGroupMessage bool                   `protobuf:"varint,2,opt,name=is_group_message,json=isGroupMessage,proto3" json:"is_group_message,omitempty"`
	FromId         int64                  `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Messages       []*Message             `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessagesWithTotal) Reset() {
	*x = MessagesWithTotal{}
	mi := &file_model_message_messages_with_total_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesWithTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesWithTotal) ProtoMessage() {}

func (x *MessagesWithTotal) ProtoReflect() protoreflect.Message {
	mi := &file_model_message_messages_with_total_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesWithTotal.ProtoReflect.Descriptor instead.
func (*MessagesWithTotal) Descriptor() ([]byte, []int) {
	return file_model_message_messages_with_total_proto_rawDescGZIP(), []int{0}
}

func (x *MessagesWithTotal) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessagesWithTotal) GetIsGroupMessage() bool {
	if x != nil {
		return x.IsGroupMessage
	}
	return false
}

func (x *MessagesWithTotal) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *MessagesWithTotal) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_model_message_messages_with_total_proto protoreflect.FileDescriptor

const file_model_message_messages_with_total_proto_rawDesc = "" +
	"\n" +
	"'model/message/messages_with_total.proto\x12\x0eim.turms.proto\x1a\x1bmodel/message/message.proto\"\xa1\x01\n" +
	"\x11MessagesWithTotal\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12(\n" +
	"\x10is_group_message\x18\x02 \x01(\bR\x0eisGroupMessage\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x03R\x06fromId\x123\n" +
	"\bmessages\x18\x04 \x03(\v2\x17.im.turms.proto.MessageR\bmessagesB[\n" +
	"6im.turms.server.common.access.client.dto.model.messageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_message_messages_with_total_proto_rawDescOnce sync.Once
	file_model_message_messages_with_total_proto_rawDescData []byte
)

func file_model_message_messages_with_total_proto_rawDescGZIP() []byte {
	file_model_message_messages_with_total_proto_rawDescOnce.Do(func() {
		file_model_message_messages_with_total_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_message_messages_with_total_proto_rawDesc), len(file_model_message_messages_with_total_proto_rawDesc)))
	})
	return file_model_message_messages_with_total_proto_rawDescData
}

var file_model_message_messages_with_total_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_message_messages_with_total_proto_goTypes = []any{
	(*MessagesWithTotal)(nil), // 0: im.turms.proto.MessagesWithTotal
	(*Message)(nil),           // 1: im.turms.proto.Message
}
var file_model_message_messages_with_total_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.MessagesWithTotal.messages:type_name -> im.turms.proto.Message
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_message_messages_with_total_proto_init() }
func file_model_message_messages_with_total_proto_init() {
	if File_model_message_messages_with_total_proto != nil {
		return
	}
	file_model_message_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_message_messages_with_total_proto_rawDesc), len(file_model_message_messages_with_total_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_message_messages_with_total_proto_goTypes,
		DependencyIndexes: file_model_message_messages_with_total_proto_depIdxs,
		MessageInfos:      file_model_message_messages_with_total_proto_msgTypes,
	}.Build()
	File_model_message_messages_with_total_proto = out.File
	file_model_message_messages_with_total_proto_goTypes = nil
	file_model_message_messages_with_total_proto_depIdxs = nil
}
