// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/message/message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	DeliveryDate     *int64                 `protobuf:"varint,2,opt,name=delivery_date,json=deliveryDate,proto3,oneof" json:"delivery_date,omitempty"`
	ModificationDate *int64                 `protobuf:"varint,3,opt,name=modification_date,json=modificationDate,proto3,oneof" json:"modification_date,omitempty"`
	Text             *string                `protobuf:"bytes,4,opt,name=text,proto3,oneof" json:"text,omitempty"`
	SenderId         *int64                 `protobuf:"varint,5,opt,name=sender_id,json=senderId,proto3,oneof" json:"sender_id,omitempty"`
	GroupId          *int64                 `protobuf:"varint,6,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	IsSystemMessage  *bool                  `protobuf:"varint,7,opt,name=is_system_message,json=isSystemMessage,proto3,oneof" json:"is_system_message,omitempty"`
	RecipientId      *int64                 `protobuf:"varint,8,opt,name=recipient_id,json=recipientId,proto3,oneof" json:"recipient_id,omitempty"`
	Records          [][]byte               `protobuf:"bytes,9,rep,name=records,proto3" json:"records,omitempty"`
	SequenceId       *int32                 `protobuf:"varint,10,opt,name=sequence_id,json=sequenceId,proto3,oneof" json:"sequence_id,omitempty"`
	PreMessageId     *int64                 `protobuf:"varint,11,opt,name=pre_message_id,json=preMessageId,proto3,oneof" json:"pre_message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_model_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_model_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_model_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Message) GetDeliveryDate() int64 {
	if x != nil && x.DeliveryDate != nil {
		return *x.DeliveryDate
	}
	return 0
}

func (x *Message) GetModificationDate() int64 {
	if x != nil && x.ModificationDate != nil {
		return *x.ModificationDate
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *Message) GetSenderId() int64 {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return 0
}

func (x *Message) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *Message) GetIsSystemMessage() bool {
	if x != nil && x.IsSystemMessage != nil {
		return *x.IsSystemMessage
	}
	return false
}

func (x *Message) GetRecipientId() int64 {
	if x != nil && x.RecipientId != nil {
		return *x.RecipientId
	}
	return 0
}

func (x *Message) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *Message) GetSequenceId() int32 {
	if x != nil && x.SequenceId != nil {
		return *x.SequenceId
	}
	return 0
}

func (x *Message) GetPreMessageId() int64 {
	if x != nil && x.PreMessageId != nil {
		return *x.PreMessageId
	}
	return 0
}

var File_model_message_message_proto protoreflect.FileDescriptor

const file_model_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1bmodel/message/message.proto\x12\x0eim.turms.proto\"\xb6\x04\n" +
	"\aMessage\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12(\n" +
	"\rdelivery_date\x18\x02 \x01(\x03H\x01R\fdeliveryDate\x88\x01\x01\x120\n" +
	"\x11modification_date\x18\x03 \x01(\x03H\x02R\x10modificationDate\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x04 \x01(\tH\x03R\x04text\x88\x01\x01\x12 \n" +
	"\tsender_id\x18\x05 \x01(\x03H\x04R\bsenderId\x88\x01\x01\x12\x1e\n" +
	"\bgroup_id\x18\x06 \x01(\x03H\x05R\agroupId\x88\x01\x01\x12/\n" +
	"\x11is_system_message\x18\a \x01(\bH\x06R\x0fisSystemMessage\x88\x01\x01\x12&\n" +
	"\frecipient_id\x18\b \x01(\x03H\aR\vrecipientId\x88\x01\x01\x12\x18\n" +
	"\arecords\x18\t \x03(\fR\arecords\x12$\n" +
	"\vsequence_id\x18\n" +
	" \x01(\x05H\bR\n" +
	"sequenceId\x88\x01\x01\x12)\n" +
	"\x0epre_message_id\x18\v \x01(\x03H\tR\fpreMessageId\x88\x01\x01B\x05\n" +
	"\x03_idB\x10\n" +
	"\x0e_delivery_dateB\x14\n" +
	"\x12_modification_dateB\a\n" +
	"\x05_textB\f\n" +
	"\n" +
	"_sender_idB\v\n" +
	"\t_group_idB\x14\n" +
	"\x12_is_system_messageB\x0f\n" +
	"\r_recipient_idB\x0e\n" +
	"\f_sequence_idB\x11\n" +
	"\x0f_pre_message_idB[\n" +
	"6im.turms.server.common.access.client.dto.model.messageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_message_message_proto_rawDescOnce sync.Once
	file_model_message_message_proto_rawDescData []byte
)

func file_model_message_message_proto_rawDescGZIP() []byte {
	file_model_message_message_proto_rawDescOnce.Do(func() {
		file_model_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_message_message_proto_rawDesc), len(file_model_message_message_proto_rawDesc)))
	})
	return file_model_message_message_proto_rawDescData
}

var file_model_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_message_message_proto_goTypes = []any{
	(*Message)(nil), // 0: im.turms.proto.Message
}
var file_model_message_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_message_message_proto_init() }
func file_model_message_message_proto_init() {
	if File_model_message_message_proto != nil {
		return
	}
	file_model_message_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_message_message_proto_rawDesc), len(file_model_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_message_message_proto_goTypes,
		DependencyIndexes: file_model_message_message_proto_depIdxs,
		MessageInfos:      file_model_message_message_proto_msgTypes,
	}.Build()
	File_model_message_message_proto = out.File
	file_model_message_message_proto_goTypes = nil
	file_model_message_message_proto_depIdxs = nil
}
