// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/user/nearby_users.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NearbyUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NearbyUsers   []*NearbyUser          `protobuf:"bytes,1,rep,name=nearby_users,json=nearbyUsers,proto3" json:"nearby_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyUsers) Reset() {
	*x = NearbyUsers{}
	mi := &file_model_user_nearby_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyUsers) ProtoMessage() {}

func (x *NearbyUsers) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_nearby_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyUsers.ProtoReflect.Descriptor instead.
func (*NearbyUsers) Descriptor() ([]byte, []int) {
	return file_model_user_nearby_users_proto_rawDescGZIP(), []int{0}
}

func (x *NearbyUsers) GetNearbyUsers() []*NearbyUser {
	if x != nil {
		return x.NearbyUsers
	}
	return nil
}

var File_model_user_nearby_users_proto protoreflect.FileDescriptor

const file_model_user_nearby_users_proto_rawDesc = "" +
	"\n" +
	"\x1dmodel/user/nearby_users.proto\x12\x0eim.turms.proto\x1a\x1cmodel/user/nearby_user.proto\"L\n" +
	"\vNearbyUsers\x12=\n" +
	"\fnearby_users\x18\x01 \x03(\v2\x1a.im.turms.proto.NearbyUserR\vnearbyUsersBX\n" +
	"3im.turms.server.common.access.client.dto.model.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_user_nearby_users_proto_rawDescOnce sync.Once
	file_model_user_nearby_users_proto_rawDescData []byte
)

func file_model_user_nearby_users_proto_rawDescGZIP() []byte {
	file_model_user_nearby_users_proto_rawDescOnce.Do(func() {
		file_model_user_nearby_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_user_nearby_users_proto_rawDesc), len(file_model_user_nearby_users_proto_rawDesc)))
	})
	return file_model_user_nearby_users_proto_rawDescData
}

var file_model_user_nearby_users_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_user_nearby_users_proto_goTypes = []any{
	(*NearbyUsers)(nil), // 0: im.turms.proto.NearbyUsers
	(*NearbyUser)(nil),  // 1: im.turms.proto.NearbyUser
}
var file_model_user_nearby_users_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.NearbyUsers.nearby_users:type_name -> im.turms.proto.NearbyUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_user_nearby_users_proto_init() }
func file_model_user_nearby_users_proto_init() {
	if File_model_user_nearby_users_proto != nil {
		return
	}
	file_model_user_nearby_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_user_nearby_users_proto_rawDesc), len(file_model_user_nearby_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_user_nearby_users_proto_goTypes,
		DependencyIndexes: file_model_user_nearby_users_proto_depIdxs,
		MessageInfos:      file_model_user_nearby_users_proto_msgTypes,
	}.Build()
	File_model_user_nearby_users_proto = out.File
	file_model_user_nearby_users_proto_goTypes = nil
	file_model_user_nearby_users_proto_depIdxs = nil
}
