// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/user/nearby_user.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NearbyUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session info
	UserId     int64       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceType *DeviceType `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3,enum=im.turms.proto.DeviceType,oneof" json:"device_type,omitempty"`
	// user info
	Info *UserInfo `protobuf:"bytes,3,opt,name=info,proto3,oneof" json:"info,omitempty"`
	// geo info
	Distance      *int32        `protobuf:"varint,4,opt,name=distance,proto3,oneof" json:"distance,omitempty"`
	Location      *UserLocation `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyUser) Reset() {
	*x = NearbyUser{}
	mi := &file_model_user_nearby_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyUser) ProtoMessage() {}

func (x *NearbyUser) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_nearby_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyUser.ProtoReflect.Descriptor instead.
func (*NearbyUser) Descriptor() ([]byte, []int) {
	return file_model_user_nearby_user_proto_rawDescGZIP(), []int{0}
}

func (x *NearbyUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NearbyUser) GetDeviceType() DeviceType {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return DeviceType_DESKTOP
}

func (x *NearbyUser) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *NearbyUser) GetDistance() int32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

func (x *NearbyUser) GetLocation() *UserLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_model_user_nearby_user_proto protoreflect.FileDescriptor

const file_model_user_nearby_user_proto_rawDesc = "" +
	"\n" +
	"\x1cmodel/user/nearby_user.proto\x12\x0eim.turms.proto\x1a\x1aconstant/device_type.proto\x1a\x1emodel/user/user_location.proto\x1a\x1amodel/user/user_info.proto\"\xad\x02\n" +
	"\n" +
	"NearbyUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12@\n" +
	"\vdevice_type\x18\x02 \x01(\x0e2\x1a.im.turms.proto.DeviceTypeH\x00R\n" +
	"deviceType\x88\x01\x01\x121\n" +
	"\x04info\x18\x03 \x01(\v2\x18.im.turms.proto.UserInfoH\x01R\x04info\x88\x01\x01\x12\x1f\n" +
	"\bdistance\x18\x04 \x01(\x05H\x02R\bdistance\x88\x01\x01\x12=\n" +
	"\blocation\x18\x05 \x01(\v2\x1c.im.turms.proto.UserLocationH\x03R\blocation\x88\x01\x01B\x0e\n" +
	"\f_device_typeB\a\n" +
	"\x05_infoB\v\n" +
	"\t_distanceB\v\n" +
	"\t_locationBX\n" +
	"3im.turms.server.common.access.client.dto.model.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_user_nearby_user_proto_rawDescOnce sync.Once
	file_model_user_nearby_user_proto_rawDescData []byte
)

func file_model_user_nearby_user_proto_rawDescGZIP() []byte {
	file_model_user_nearby_user_proto_rawDescOnce.Do(func() {
		file_model_user_nearby_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_user_nearby_user_proto_rawDesc), len(file_model_user_nearby_user_proto_rawDesc)))
	})
	return file_model_user_nearby_user_proto_rawDescData
}

var file_model_user_nearby_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_user_nearby_user_proto_goTypes = []any{
	(*NearbyUser)(nil),   // 0: im.turms.proto.NearbyUser
	(DeviceType)(0),      // 1: im.turms.proto.DeviceType
	(*UserInfo)(nil),     // 2: im.turms.proto.UserInfo
	(*UserLocation)(nil), // 3: im.turms.proto.UserLocation
}
var file_model_user_nearby_user_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.NearbyUser.device_type:type_name -> im.turms.proto.DeviceType
	2, // 1: im.turms.proto.NearbyUser.info:type_name -> im.turms.proto.UserInfo
	3, // 2: im.turms.proto.NearbyUser.location:type_name -> im.turms.proto.UserLocation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_user_nearby_user_proto_init() }
func file_model_user_nearby_user_proto_init() {
	if File_model_user_nearby_user_proto != nil {
		return
	}
	file_constant_device_type_proto_init()
	file_model_user_user_location_proto_init()
	file_model_user_user_info_proto_init()
	file_model_user_nearby_user_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_user_nearby_user_proto_rawDesc), len(file_model_user_nearby_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_user_nearby_user_proto_goTypes,
		DependencyIndexes: file_model_user_nearby_user_proto_depIdxs,
		MessageInfos:      file_model_user_nearby_user_proto_msgTypes,
	}.Build()
	File_model_user_nearby_user_proto = out.File
	file_model_user_nearby_user_proto_goTypes = nil
	file_model_user_nearby_user_proto_depIdxs = nil
}
