// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/conversation/private_conversation.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateConversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ReadDate      int64                  `protobuf:"varint,3,opt,name=read_date,json=readDate,proto3" json:"read_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateConversation) Reset() {
	*x = PrivateConversation{}
	mi := &file_model_conversation_private_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateConversation) ProtoMessage() {}

func (x *PrivateConversation) ProtoReflect() protoreflect.Message {
	mi := &file_model_conversation_private_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateConversation.ProtoReflect.Descriptor instead.
func (*PrivateConversation) Descriptor() ([]byte, []int) {
	return file_model_conversation_private_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateConversation) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *PrivateConversation) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *PrivateConversation) GetReadDate() int64 {
	if x != nil {
		return x.ReadDate
	}
	return 0
}

var File_model_conversation_private_conversation_proto protoreflect.FileDescriptor

const file_model_conversation_private_conversation_proto_rawDesc = "" +
	"\n" +
	"-model/conversation/private_conversation.proto\x12\x0eim.turms.proto\"j\n" +
	"\x13PrivateConversation\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x1b\n" +
	"\tread_date\x18\x03 \x01(\x03R\breadDateB`\n" +
	";im.turms.server.common.access.client.dto.model.conversationP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_conversation_private_conversation_proto_rawDescOnce sync.Once
	file_model_conversation_private_conversation_proto_rawDescData []byte
)

func file_model_conversation_private_conversation_proto_rawDescGZIP() []byte {
	file_model_conversation_private_conversation_proto_rawDescOnce.Do(func() {
		file_model_conversation_private_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_conversation_private_conversation_proto_rawDesc), len(file_model_conversation_private_conversation_proto_rawDesc)))
	})
	return file_model_conversation_private_conversation_proto_rawDescData
}

var file_model_conversation_private_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_conversation_private_conversation_proto_goTypes = []any{
	(*PrivateConversation)(nil), // 0: im.turms.proto.PrivateConversation
}
var file_model_conversation_private_conversation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_conversation_private_conversation_proto_init() }
func file_model_conversation_private_conversation_proto_init() {
	if File_model_conversation_private_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_conversation_private_conversation_proto_rawDesc), len(file_model_conversation_private_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_conversation_private_conversation_proto_goTypes,
		DependencyIndexes: file_model_conversation_private_conversation_proto_depIdxs,
		MessageInfos:      file_model_conversation_private_conversation_proto_msgTypes,
	}.Build()
	File_model_conversation_private_conversation_proto = out.File
	file_model_conversation_private_conversation_proto_goTypes = nil
	file_model_conversation_private_conversation_proto_depIdxs = nil
}
