// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/message/query_messages_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter
	Ids               []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	AreGroupMessages  *bool   `protobuf:"varint,2,opt,name=are_group_messages,json=areGroupMessages,proto3,oneof" json:"are_group_messages,omitempty"`
	AreSystemMessages *bool   `protobuf:"varint,3,opt,name=are_system_messages,json=areSystemMessages,proto3,oneof" json:"are_system_messages,omitempty"`
	FromIds           []int64 `protobuf:"varint,4,rep,packed,name=from_ids,json=fromIds,proto3" json:"from_ids,omitempty"`
	DeliveryDateStart *int64  `protobuf:"varint,5,opt,name=delivery_date_start,json=deliveryDateStart,proto3,oneof" json:"delivery_date_start,omitempty"`
	DeliveryDateEnd   *int64  `protobuf:"varint,6,opt,name=delivery_date_end,json=deliveryDateEnd,proto3,oneof" json:"delivery_date_end,omitempty"`
	// Option
	MaxCount *int32 `protobuf:"varint,7,opt,name=max_count,json=maxCount,proto3,oneof" json:"max_count,omitempty"`
	// Command
	WithTotal bool `protobuf:"varint,8,opt,name=with_total,json=withTotal,proto3" json:"with_total,omitempty"`
	// Option
	// TODO: reorder
	Descending    *bool `protobuf:"varint,9,opt,name=descending,proto3,oneof" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMessagesRequest) Reset() {
	*x = QueryMessagesRequest{}
	mi := &file_request_message_query_messages_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessagesRequest) ProtoMessage() {}

func (x *QueryMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_message_query_messages_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessagesRequest.ProtoReflect.Descriptor instead.
func (*QueryMessagesRequest) Descriptor() ([]byte, []int) {
	return file_request_message_query_messages_request_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMessagesRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *QueryMessagesRequest) GetAreGroupMessages() bool {
	if x != nil && x.AreGroupMessages != nil {
		return *x.AreGroupMessages
	}
	return false
}

func (x *QueryMessagesRequest) GetAreSystemMessages() bool {
	if x != nil && x.AreSystemMessages != nil {
		return *x.AreSystemMessages
	}
	return false
}

func (x *QueryMessagesRequest) GetFromIds() []int64 {
	if x != nil {
		return x.FromIds
	}
	return nil
}

func (x *QueryMessagesRequest) GetDeliveryDateStart() int64 {
	if x != nil && x.DeliveryDateStart != nil {
		return *x.DeliveryDateStart
	}
	return 0
}

func (x *QueryMessagesRequest) GetDeliveryDateEnd() int64 {
	if x != nil && x.DeliveryDateEnd != nil {
		return *x.DeliveryDateEnd
	}
	return 0
}

func (x *QueryMessagesRequest) GetMaxCount() int32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	return 0
}

func (x *QueryMessagesRequest) GetWithTotal() bool {
	if x != nil {
		return x.WithTotal
	}
	return false
}

func (x *QueryMessagesRequest) GetDescending() bool {
	if x != nil && x.Descending != nil {
		return *x.Descending
	}
	return false
}

var File_request_message_query_messages_request_proto protoreflect.FileDescriptor

const file_request_message_query_messages_request_proto_rawDesc = "" +
	"\n" +
	",request/message/query_messages_request.proto\x12\x0eim.turms.proto\"\xf1\x03\n" +
	"\x14QueryMessagesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\x121\n" +
	"\x12are_group_messages\x18\x02 \x01(\bH\x00R\x10areGroupMessages\x88\x01\x01\x123\n" +
	"\x13are_system_messages\x18\x03 \x01(\bH\x01R\x11areSystemMessages\x88\x01\x01\x12\x19\n" +
	"\bfrom_ids\x18\x04 \x03(\x03R\afromIds\x123\n" +
	"\x13delivery_date_start\x18\x05 \x01(\x03H\x02R\x11deliveryDateStart\x88\x01\x01\x12/\n" +
	"\x11delivery_date_end\x18\x06 \x01(\x03H\x03R\x0fdeliveryDateEnd\x88\x01\x01\x12 \n" +
	"\tmax_count\x18\a \x01(\x05H\x04R\bmaxCount\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"with_total\x18\b \x01(\bR\twithTotal\x12#\n" +
	"\n" +
	"descending\x18\t \x01(\bH\x05R\n" +
	"descending\x88\x01\x01B\x15\n" +
	"\x13_are_group_messagesB\x16\n" +
	"\x14_are_system_messagesB\x16\n" +
	"\x14_delivery_date_startB\x14\n" +
	"\x12_delivery_date_endB\f\n" +
	"\n" +
	"_max_countB\r\n" +
	"\v_descendingB]\n" +
	"8im.turms.server.common.access.client.dto.request.messageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_message_query_messages_request_proto_rawDescOnce sync.Once
	file_request_message_query_messages_request_proto_rawDescData []byte
)

func file_request_message_query_messages_request_proto_rawDescGZIP() []byte {
	file_request_message_query_messages_request_proto_rawDescOnce.Do(func() {
		file_request_message_query_messages_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_message_query_messages_request_proto_rawDesc), len(file_request_message_query_messages_request_proto_rawDesc)))
	})
	return file_request_message_query_messages_request_proto_rawDescData
}

var file_request_message_query_messages_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_message_query_messages_request_proto_goTypes = []any{
	(*QueryMessagesRequest)(nil), // 0: im.turms.proto.QueryMessagesRequest
}
var file_request_message_query_messages_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_message_query_messages_request_proto_init() }
func file_request_message_query_messages_request_proto_init() {
	if File_request_message_query_messages_request_proto != nil {
		return
	}
	file_request_message_query_messages_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_message_query_messages_request_proto_rawDesc), len(file_request_message_query_messages_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_message_query_messages_request_proto_goTypes,
		DependencyIndexes: file_request_message_query_messages_request_proto_depIdxs,
		MessageInfos:      file_request_message_query_messages_request_proto_msgTypes,
	}.Build()
	File_request_message_query_messages_request_proto = out.File
	file_request_message_query_messages_request_proto_goTypes = nil
	file_request_message_query_messages_request_proto_depIdxs = nil
}
