// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/relationship/query_relationships_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRelationshipsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserIds         []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Blocked         *bool                  `protobuf:"varint,2,opt,name=blocked,proto3,oneof" json:"blocked,omitempty"`
	GroupIndexes    []int32                `protobuf:"varint,3,rep,packed,name=group_indexes,json=groupIndexes,proto3" json:"group_indexes,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,4,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	Name            *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryRelationshipsRequest) Reset() {
	*x = QueryRelationshipsRequest{}
	mi := &file_request_user_relationship_query_relationships_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRelationshipsRequest) ProtoMessage() {}

func (x *QueryRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_relationship_query_relationships_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*QueryRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_request_user_relationship_query_relationships_request_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRelationshipsRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *QueryRelationshipsRequest) GetBlocked() bool {
	if x != nil && x.Blocked != nil {
		return *x.Blocked
	}
	return false
}

func (x *QueryRelationshipsRequest) GetGroupIndexes() []int32 {
	if x != nil {
		return x.GroupIndexes
	}
	return nil
}

func (x *QueryRelationshipsRequest) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

func (x *QueryRelationshipsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_request_user_relationship_query_relationships_request_proto protoreflect.FileDescriptor

const file_request_user_relationship_query_relationships_request_proto_rawDesc = "" +
	"\n" +
	";request/user/relationship/query_relationships_request.proto\x12\x0eim.turms.proto\"\xef\x01\n" +
	"\x19QueryRelationshipsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x1d\n" +
	"\ablocked\x18\x02 \x01(\bH\x00R\ablocked\x88\x01\x01\x12#\n" +
	"\rgroup_indexes\x18\x03 \x03(\x05R\fgroupIndexes\x12/\n" +
	"\x11last_updated_date\x18\x04 \x01(\x03H\x01R\x0flastUpdatedDate\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x02R\x04name\x88\x01\x01B\n" +
	"\n" +
	"\b_blockedB\x14\n" +
	"\x12_last_updated_dateB\a\n" +
	"\x05_nameBg\n" +
	"Bim.turms.server.common.access.client.dto.request.user.relationshipP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_relationship_query_relationships_request_proto_rawDescOnce sync.Once
	file_request_user_relationship_query_relationships_request_proto_rawDescData []byte
)

func file_request_user_relationship_query_relationships_request_proto_rawDescGZIP() []byte {
	file_request_user_relationship_query_relationships_request_proto_rawDescOnce.Do(func() {
		file_request_user_relationship_query_relationships_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_relationship_query_relationships_request_proto_rawDesc), len(file_request_user_relationship_query_relationships_request_proto_rawDesc)))
	})
	return file_request_user_relationship_query_relationships_request_proto_rawDescData
}

var file_request_user_relationship_query_relationships_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_user_relationship_query_relationships_request_proto_goTypes = []any{
	(*QueryRelationshipsRequest)(nil), // 0: im.turms.proto.QueryRelationshipsRequest
}
var file_request_user_relationship_query_relationships_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_user_relationship_query_relationships_request_proto_init() }
func file_request_user_relationship_query_relationships_request_proto_init() {
	if File_request_user_relationship_query_relationships_request_proto != nil {
		return
	}
	file_request_user_relationship_query_relationships_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_relationship_query_relationships_request_proto_rawDesc), len(file_request_user_relationship_query_relationships_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_relationship_query_relationships_request_proto_goTypes,
		DependencyIndexes: file_request_user_relationship_query_relationships_request_proto_depIdxs,
		MessageInfos:      file_request_user_relationship_query_relationships_request_proto_msgTypes,
	}.Build()
	File_request_user_relationship_query_relationships_request_proto = out.File
	file_request_user_relationship_query_relationships_request_proto_goTypes = nil
	file_request_user_relationship_query_relationships_request_proto_depIdxs = nil
}
