// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/enrollment/query_group_invitations_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryGroupInvitationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         *int64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3,oneof" json:"group_id,omitempty"`
	AreSentByMe     *bool                  `protobuf:"varint,2,opt,name=are_sent_by_me,json=areSentByMe,proto3,oneof" json:"are_sent_by_me,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,3,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryGroupInvitationsRequest) Reset() {
	*x = QueryGroupInvitationsRequest{}
	mi := &file_request_group_enrollment_query_group_invitations_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupInvitationsRequest) ProtoMessage() {}

func (x *QueryGroupInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_enrollment_query_group_invitations_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupInvitationsRequest.ProtoReflect.Descriptor instead.
func (*QueryGroupInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_request_group_enrollment_query_group_invitations_request_proto_rawDescGZIP(), []int{0}
}

func (x *QueryGroupInvitationsRequest) GetGroupId() int64 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *QueryGroupInvitationsRequest) GetAreSentByMe() bool {
	if x != nil && x.AreSentByMe != nil {
		return *x.AreSentByMe
	}
	return false
}

func (x *QueryGroupInvitationsRequest) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

var File_request_group_enrollment_query_group_invitations_request_proto protoreflect.FileDescriptor

const file_request_group_enrollment_query_group_invitations_request_proto_rawDesc = "" +
	"\n" +
	">request/group/enrollment/query_group_invitations_request.proto\x12\x0eim.turms.proto\"\xcf\x01\n" +
	"\x1cQueryGroupInvitationsRequest\x12\x1e\n" +
	"\bgroup_id\x18\x01 \x01(\x03H\x00R\agroupId\x88\x01\x01\x12(\n" +
	"\x0eare_sent_by_me\x18\x02 \x01(\bH\x01R\vareSentByMe\x88\x01\x01\x12/\n" +
	"\x11last_updated_date\x18\x03 \x01(\x03H\x02R\x0flastUpdatedDate\x88\x01\x01B\v\n" +
	"\t_group_idB\x11\n" +
	"\x0f_are_sent_by_meB\x14\n" +
	"\x12_last_updated_dateBf\n" +
	"Aim.turms.server.common.access.client.dto.request.group.enrollmentP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_enrollment_query_group_invitations_request_proto_rawDescOnce sync.Once
	file_request_group_enrollment_query_group_invitations_request_proto_rawDescData []byte
)

func file_request_group_enrollment_query_group_invitations_request_proto_rawDescGZIP() []byte {
	file_request_group_enrollment_query_group_invitations_request_proto_rawDescOnce.Do(func() {
		file_request_group_enrollment_query_group_invitations_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_enrollment_query_group_invitations_request_proto_rawDesc), len(file_request_group_enrollment_query_group_invitations_request_proto_rawDesc)))
	})
	return file_request_group_enrollment_query_group_invitations_request_proto_rawDescData
}

var file_request_group_enrollment_query_group_invitations_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_enrollment_query_group_invitations_request_proto_goTypes = []any{
	(*QueryGroupInvitationsRequest)(nil), // 0: im.turms.proto.QueryGroupInvitationsRequest
}
var file_request_group_enrollment_query_group_invitations_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_group_enrollment_query_group_invitations_request_proto_init() }
func file_request_group_enrollment_query_group_invitations_request_proto_init() {
	if File_request_group_enrollment_query_group_invitations_request_proto != nil {
		return
	}
	file_request_group_enrollment_query_group_invitations_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_enrollment_query_group_invitations_request_proto_rawDesc), len(file_request_group_enrollment_query_group_invitations_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_enrollment_query_group_invitations_request_proto_goTypes,
		DependencyIndexes: file_request_group_enrollment_query_group_invitations_request_proto_depIdxs,
		MessageInfos:      file_request_group_enrollment_query_group_invitations_request_proto_msgTypes,
	}.Build()
	File_request_group_enrollment_query_group_invitations_request_proto = out.File
	file_request_group_enrollment_query_group_invitations_request_proto_goTypes = nil
	file_request_group_enrollment_query_group_invitations_request_proto_depIdxs = nil
}
