// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/query_nearby_users_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryNearbyUsersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Latitude        float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	MaxCount        *int32                 `protobuf:"varint,3,opt,name=max_count,json=maxCount,proto3,oneof" json:"max_count,omitempty"`
	MaxDistance     *int32                 `protobuf:"varint,4,opt,name=max_distance,json=maxDistance,proto3,oneof" json:"max_distance,omitempty"`
	WithCoordinates *bool                  `protobuf:"varint,5,opt,name=with_coordinates,json=withCoordinates,proto3,oneof" json:"with_coordinates,omitempty"`
	WithDistance    *bool                  `protobuf:"varint,6,opt,name=with_distance,json=withDistance,proto3,oneof" json:"with_distance,omitempty"`
	WithUserInfo    *bool                  `protobuf:"varint,7,opt,name=with_user_info,json=withUserInfo,proto3,oneof" json:"with_user_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryNearbyUsersRequest) Reset() {
	*x = QueryNearbyUsersRequest{}
	mi := &file_request_user_query_nearby_users_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNearbyUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNearbyUsersRequest) ProtoMessage() {}

func (x *QueryNearbyUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_query_nearby_users_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNearbyUsersRequest.ProtoReflect.Descriptor instead.
func (*QueryNearbyUsersRequest) Descriptor() ([]byte, []int) {
	return file_request_user_query_nearby_users_request_proto_rawDescGZIP(), []int{0}
}

func (x *QueryNearbyUsersRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *QueryNearbyUsersRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *QueryNearbyUsersRequest) GetMaxCount() int32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	return 0
}

func (x *QueryNearbyUsersRequest) GetMaxDistance() int32 {
	if x != nil && x.MaxDistance != nil {
		return *x.MaxDistance
	}
	return 0
}

func (x *QueryNearbyUsersRequest) GetWithCoordinates() bool {
	if x != nil && x.WithCoordinates != nil {
		return *x.WithCoordinates
	}
	return false
}

func (x *QueryNearbyUsersRequest) GetWithDistance() bool {
	if x != nil && x.WithDistance != nil {
		return *x.WithDistance
	}
	return false
}

func (x *QueryNearbyUsersRequest) GetWithUserInfo() bool {
	if x != nil && x.WithUserInfo != nil {
		return *x.WithUserInfo
	}
	return false
}

var File_request_user_query_nearby_users_request_proto protoreflect.FileDescriptor

const file_request_user_query_nearby_users_request_proto_rawDesc = "" +
	"\n" +
	"-request/user/query_nearby_users_request.proto\x12\x0eim.turms.proto\"\xfb\x02\n" +
	"\x17QueryNearbyUsersRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12 \n" +
	"\tmax_count\x18\x03 \x01(\x05H\x00R\bmaxCount\x88\x01\x01\x12&\n" +
	"\fmax_distance\x18\x04 \x01(\x05H\x01R\vmaxDistance\x88\x01\x01\x12.\n" +
	"\x10with_coordinates\x18\x05 \x01(\bH\x02R\x0fwithCoordinates\x88\x01\x01\x12(\n" +
	"\rwith_distance\x18\x06 \x01(\bH\x03R\fwithDistance\x88\x01\x01\x12)\n" +
	"\x0ewith_user_info\x18\a \x01(\bH\x04R\fwithUserInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_max_countB\x0f\n" +
	"\r_max_distanceB\x13\n" +
	"\x11_with_coordinatesB\x10\n" +
	"\x0e_with_distanceB\x11\n" +
	"\x0f_with_user_infoBZ\n" +
	"5im.turms.server.common.access.client.dto.request.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_query_nearby_users_request_proto_rawDescOnce sync.Once
	file_request_user_query_nearby_users_request_proto_rawDescData []byte
)

func file_request_user_query_nearby_users_request_proto_rawDescGZIP() []byte {
	file_request_user_query_nearby_users_request_proto_rawDescOnce.Do(func() {
		file_request_user_query_nearby_users_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_query_nearby_users_request_proto_rawDesc), len(file_request_user_query_nearby_users_request_proto_rawDesc)))
	})
	return file_request_user_query_nearby_users_request_proto_rawDescData
}

var file_request_user_query_nearby_users_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_user_query_nearby_users_request_proto_goTypes = []any{
	(*QueryNearbyUsersRequest)(nil), // 0: im.turms.proto.QueryNearbyUsersRequest
}
var file_request_user_query_nearby_users_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_user_query_nearby_users_request_proto_init() }
func file_request_user_query_nearby_users_request_proto_init() {
	if File_request_user_query_nearby_users_request_proto != nil {
		return
	}
	file_request_user_query_nearby_users_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_query_nearby_users_request_proto_rawDesc), len(file_request_user_query_nearby_users_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_query_nearby_users_request_proto_goTypes,
		DependencyIndexes: file_request_user_query_nearby_users_request_proto_depIdxs,
		MessageInfos:      file_request_user_query_nearby_users_request_proto_msgTypes,
	}.Build()
	File_request_user_query_nearby_users_request_proto = out.File
	file_request_user_query_nearby_users_request_proto_goTypes = nil
	file_request_user_query_nearby_users_request_proto_depIdxs = nil
}
