// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/member/query_group_members_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryGroupMembersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,2,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	MemberIds       []int64                `protobuf:"varint,3,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	WithStatus      *bool                  `protobuf:"varint,4,opt,name=with_status,json=withStatus,proto3,oneof" json:"with_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryGroupMembersRequest) Reset() {
	*x = QueryGroupMembersRequest{}
	mi := &file_request_group_member_query_group_members_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGroupMembersRequest) ProtoMessage() {}

func (x *QueryGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_member_query_group_members_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*QueryGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_request_group_member_query_group_members_request_proto_rawDescGZIP(), []int{0}
}

func (x *QueryGroupMembersRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *QueryGroupMembersRequest) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

func (x *QueryGroupMembersRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *QueryGroupMembersRequest) GetWithStatus() bool {
	if x != nil && x.WithStatus != nil {
		return *x.WithStatus
	}
	return false
}

var File_request_group_member_query_group_members_request_proto protoreflect.FileDescriptor

const file_request_group_member_query_group_members_request_proto_rawDesc = "" +
	"\n" +
	"6request/group/member/query_group_members_request.proto\x12\x0eim.turms.proto\"\xd1\x01\n" +
	"\x18QueryGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12/\n" +
	"\x11last_updated_date\x18\x02 \x01(\x03H\x00R\x0flastUpdatedDate\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\x03R\tmemberIds\x12$\n" +
	"\vwith_status\x18\x04 \x01(\bH\x01R\n" +
	"withStatus\x88\x01\x01B\x14\n" +
	"\x12_last_updated_dateB\x0e\n" +
	"\f_with_statusBb\n" +
	"=im.turms.server.common.access.client.dto.request.group.memberP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_member_query_group_members_request_proto_rawDescOnce sync.Once
	file_request_group_member_query_group_members_request_proto_rawDescData []byte
)

func file_request_group_member_query_group_members_request_proto_rawDescGZIP() []byte {
	file_request_group_member_query_group_members_request_proto_rawDescOnce.Do(func() {
		file_request_group_member_query_group_members_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_member_query_group_members_request_proto_rawDesc), len(file_request_group_member_query_group_members_request_proto_rawDesc)))
	})
	return file_request_group_member_query_group_members_request_proto_rawDescData
}

var file_request_group_member_query_group_members_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_member_query_group_members_request_proto_goTypes = []any{
	(*QueryGroupMembersRequest)(nil), // 0: im.turms.proto.QueryGroupMembersRequest
}
var file_request_group_member_query_group_members_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_group_member_query_group_members_request_proto_init() }
func file_request_group_member_query_group_members_request_proto_init() {
	if File_request_group_member_query_group_members_request_proto != nil {
		return
	}
	file_request_group_member_query_group_members_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_member_query_group_members_request_proto_rawDesc), len(file_request_group_member_query_group_members_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_member_query_group_members_request_proto_goTypes,
		DependencyIndexes: file_request_group_member_query_group_members_request_proto_depIdxs,
		MessageInfos:      file_request_group_member_query_group_members_request_proto_msgTypes,
	}.Build()
	File_request_group_member_query_group_members_request_proto = out.File
	file_request_group_member_query_group_members_request_proto_goTypes = nil
	file_request_group_member_query_group_members_request_proto_depIdxs = nil
}
