// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/storage/storage_resource_infos.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageResourceInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*StorageResourceInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResourceInfos) Reset() {
	*x = StorageResourceInfos{}
	mi := &file_model_storage_storage_resource_infos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResourceInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResourceInfos) ProtoMessage() {}

func (x *StorageResourceInfos) ProtoReflect() protoreflect.Message {
	mi := &file_model_storage_storage_resource_infos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResourceInfos.ProtoReflect.Descriptor instead.
func (*StorageResourceInfos) Descriptor() ([]byte, []int) {
	return file_model_storage_storage_resource_infos_proto_rawDescGZIP(), []int{0}
}

func (x *StorageResourceInfos) GetInfos() []*StorageResourceInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_model_storage_storage_resource_infos_proto protoreflect.FileDescriptor

const file_model_storage_storage_resource_infos_proto_rawDesc = "" +
	"\n" +
	"*model/storage/storage_resource_infos.proto\x12\x0eim.turms.proto\x1a)model/storage/storage_resource_info.proto\"Q\n" +
	"\x14StorageResourceInfos\x129\n" +
	"\x05infos\x18\x01 \x03(\v2#.im.turms.proto.StorageResourceInfoR\x05infosB[\n" +
	"6im.turms.server.common.access.client.dto.model.storageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_storage_storage_resource_infos_proto_rawDescOnce sync.Once
	file_model_storage_storage_resource_infos_proto_rawDescData []byte
)

func file_model_storage_storage_resource_infos_proto_rawDescGZIP() []byte {
	file_model_storage_storage_resource_infos_proto_rawDescOnce.Do(func() {
		file_model_storage_storage_resource_infos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_storage_storage_resource_infos_proto_rawDesc), len(file_model_storage_storage_resource_infos_proto_rawDesc)))
	})
	return file_model_storage_storage_resource_infos_proto_rawDescData
}

var file_model_storage_storage_resource_infos_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_storage_storage_resource_infos_proto_goTypes = []any{
	(*StorageResourceInfos)(nil), // 0: im.turms.proto.StorageResourceInfos
	(*StorageResourceInfo)(nil),  // 1: im.turms.proto.StorageResourceInfo
}
var file_model_storage_storage_resource_infos_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.StorageResourceInfos.infos:type_name -> im.turms.proto.StorageResourceInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_storage_storage_resource_infos_proto_init() }
func file_model_storage_storage_resource_infos_proto_init() {
	if File_model_storage_storage_resource_infos_proto != nil {
		return
	}
	file_model_storage_storage_resource_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_storage_storage_resource_infos_proto_rawDesc), len(file_model_storage_storage_resource_infos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_storage_storage_resource_infos_proto_goTypes,
		DependencyIndexes: file_model_storage_storage_resource_infos_proto_depIdxs,
		MessageInfos:      file_model_storage_storage_resource_infos_proto_msgTypes,
	}.Build()
	File_model_storage_storage_resource_infos_proto = out.File
	file_model_storage_storage_resource_infos_proto_goTypes = nil
	file_model_storage_storage_resource_infos_proto_depIdxs = nil
}
