// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: constant/storage_resource_type.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageResourceType int32

const (
	StorageResourceType_USER_PROFILE_PICTURE  StorageResourceType = 0
	StorageResourceType_GROUP_PROFILE_PICTURE StorageResourceType = 1
	StorageResourceType_MESSAGE_ATTACHMENT    StorageResourceType = 2
)

// Enum value maps for StorageResourceType.
var (
	StorageResourceType_name = map[int32]string{
		0: "USER_PROFILE_PICTURE",
		1: "GROUP_PROFILE_PICTURE",
		2: "MESSAGE_ATTACHMENT",
	}
	StorageResourceType_value = map[string]int32{
		"USER_PROFILE_PICTURE":  0,
		"GROUP_PROFILE_PICTURE": 1,
		"MESSAGE_ATTACHMENT":    2,
	}
)

func (x StorageResourceType) Enum() *StorageResourceType {
	p := new(StorageResourceType)
	*p = x
	return p
}

func (x StorageResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_constant_storage_resource_type_proto_enumTypes[0].Descriptor()
}

func (StorageResourceType) Type() protoreflect.EnumType {
	return &file_constant_storage_resource_type_proto_enumTypes[0]
}

func (x StorageResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageResourceType.Descriptor instead.
func (StorageResourceType) EnumDescriptor() ([]byte, []int) {
	return file_constant_storage_resource_type_proto_rawDescGZIP(), []int{0}
}

var File_constant_storage_resource_type_proto protoreflect.FileDescriptor

const file_constant_storage_resource_type_proto_rawDesc = "" +
	"\n" +
	"$constant/storage_resource_type.proto\x12\x0eim.turms.proto*b\n" +
	"\x13StorageResourceType\x12\x18\n" +
	"\x14USER_PROFILE_PICTURE\x10\x00\x12\x19\n" +
	"\x15GROUP_PROFILE_PICTURE\x10\x01\x12\x16\n" +
	"\x12MESSAGE_ATTACHMENT\x10\x02BV\n" +
	"1im.turms.server.common.access.client.dto.constantP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_constant_storage_resource_type_proto_rawDescOnce sync.Once
	file_constant_storage_resource_type_proto_rawDescData []byte
)

func file_constant_storage_resource_type_proto_rawDescGZIP() []byte {
	file_constant_storage_resource_type_proto_rawDescOnce.Do(func() {
		file_constant_storage_resource_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constant_storage_resource_type_proto_rawDesc), len(file_constant_storage_resource_type_proto_rawDesc)))
	})
	return file_constant_storage_resource_type_proto_rawDescData
}

var file_constant_storage_resource_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constant_storage_resource_type_proto_goTypes = []any{
	(StorageResourceType)(0), // 0: im.turms.proto.StorageResourceType
}
var file_constant_storage_resource_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constant_storage_resource_type_proto_init() }
func file_constant_storage_resource_type_proto_init() {
	if File_constant_storage_resource_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constant_storage_resource_type_proto_rawDesc), len(file_constant_storage_resource_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constant_storage_resource_type_proto_goTypes,
		DependencyIndexes: file_constant_storage_resource_type_proto_depIdxs,
		EnumInfos:         file_constant_storage_resource_type_proto_enumTypes,
	}.Build()
	File_constant_storage_resource_type_proto = out.File
	file_constant_storage_resource_type_proto_goTypes = nil
	file_constant_storage_resource_type_proto_depIdxs = nil
}
