// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: notification/turms_notification.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TurmsNotification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common => [1, 3]
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Response => [4, 9]
	// "request_id" is used to tell the client that
	// this notification is a response to the specific request
	RequestId *int64                  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	Code      *int32                  `protobuf:"varint,5,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Reason    *string                 `protobuf:"bytes,6,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	Data      *TurmsNotification_Data `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	// Notification => [10, 15]
	// "requester_id" only exists when a requester triggers a notification to its recipients
	// Note: Do not move "requester_id" to TurmsRequest because it requires rebuilding
	// a new TurmsNotification when recipients need "requester_id".
	RequesterId    *int64        `protobuf:"varint,10,opt,name=requester_id,json=requesterId,proto3,oneof" json:"requester_id,omitempty"`
	CloseStatus    *int32        `protobuf:"varint,11,opt,name=close_status,json=closeStatus,proto3,oneof" json:"close_status,omitempty"`
	RelayedRequest *TurmsRequest `protobuf:"bytes,12,opt,name=relayed_request,json=relayedRequest,proto3" json:"relayed_request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TurmsNotification) Reset() {
	*x = TurmsNotification{}
	mi := &file_notification_turms_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurmsNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurmsNotification) ProtoMessage() {}

func (x *TurmsNotification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_turms_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurmsNotification.ProtoReflect.Descriptor instead.
func (*TurmsNotification) Descriptor() ([]byte, []int) {
	return file_notification_turms_notification_proto_rawDescGZIP(), []int{0}
}

func (x *TurmsNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TurmsNotification) GetRequestId() int64 {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return 0
}

func (x *TurmsNotification) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *TurmsNotification) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *TurmsNotification) GetData() *TurmsNotification_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TurmsNotification) GetRequesterId() int64 {
	if x != nil && x.RequesterId != nil {
		return *x.RequesterId
	}
	return 0
}

func (x *TurmsNotification) GetCloseStatus() int32 {
	if x != nil && x.CloseStatus != nil {
		return *x.CloseStatus
	}
	return 0
}

func (x *TurmsNotification) GetRelayedRequest() *TurmsRequest {
	if x != nil {
		return x.RelayedRequest
	}
	return nil
}

type TurmsNotification_Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TurmsNotification_Data_Long
	//	*TurmsNotification_Data_String_
	//	*TurmsNotification_Data_LongsWithVersion
	//	*TurmsNotification_Data_StringsWithVersion
	//	*TurmsNotification_Data_Conversations
	//	*TurmsNotification_Data_Messages
	//	*TurmsNotification_Data_MessagesWithTotalList
	//	*TurmsNotification_Data_UserSession
	//	*TurmsNotification_Data_UserInfosWithVersion
	//	*TurmsNotification_Data_UserOnlineStatuses
	//	*TurmsNotification_Data_UserFriendRequestsWithVersion
	//	*TurmsNotification_Data_UserRelationshipGroupsWithVersion
	//	*TurmsNotification_Data_UserRelationshipsWithVersion
	//	*TurmsNotification_Data_NearbyUsers
	//	*TurmsNotification_Data_GroupInvitationsWithVersion
	//	*TurmsNotification_Data_GroupJoinQuestionAnswerResult
	//	*TurmsNotification_Data_GroupJoinRequestsWithVersion
	//	*TurmsNotification_Data_GroupJoinQuestionsWithVersion
	//	*TurmsNotification_Data_GroupMembersWithVersion
	//	*TurmsNotification_Data_GroupsWithVersion
	//	*TurmsNotification_Data_Meetings
	//	*TurmsNotification_Data_StorageResourceInfos
	Kind          isTurmsNotification_Data_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurmsNotification_Data) Reset() {
	*x = TurmsNotification_Data{}
	mi := &file_notification_turms_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurmsNotification_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurmsNotification_Data) ProtoMessage() {}

func (x *TurmsNotification_Data) ProtoReflect() protoreflect.Message {
	mi := &file_notification_turms_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurmsNotification_Data.ProtoReflect.Descriptor instead.
func (*TurmsNotification_Data) Descriptor() ([]byte, []int) {
	return file_notification_turms_notification_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TurmsNotification_Data) GetKind() isTurmsNotification_Data_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TurmsNotification_Data) GetLong() int64 {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_Long); ok {
			return x.Long
		}
	}
	return 0
}

func (x *TurmsNotification_Data) GetString_() string {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *TurmsNotification_Data) GetLongsWithVersion() *LongsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_LongsWithVersion); ok {
			return x.LongsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetStringsWithVersion() *StringsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_StringsWithVersion); ok {
			return x.StringsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetConversations() *Conversations {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_Conversations); ok {
			return x.Conversations
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetMessages() *Messages {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_Messages); ok {
			return x.Messages
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetMessagesWithTotalList() *MessagesWithTotalList {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_MessagesWithTotalList); ok {
			return x.MessagesWithTotalList
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetUserSession() *UserSession {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_UserSession); ok {
			return x.UserSession
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetUserInfosWithVersion() *UserInfosWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_UserInfosWithVersion); ok {
			return x.UserInfosWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetUserOnlineStatuses() *UserOnlineStatuses {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_UserOnlineStatuses); ok {
			return x.UserOnlineStatuses
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetUserFriendRequestsWithVersion() *UserFriendRequestsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_UserFriendRequestsWithVersion); ok {
			return x.UserFriendRequestsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetUserRelationshipGroupsWithVersion() *UserRelationshipGroupsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_UserRelationshipGroupsWithVersion); ok {
			return x.UserRelationshipGroupsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetUserRelationshipsWithVersion() *UserRelationshipsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_UserRelationshipsWithVersion); ok {
			return x.UserRelationshipsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetNearbyUsers() *NearbyUsers {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_NearbyUsers); ok {
			return x.NearbyUsers
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetGroupInvitationsWithVersion() *GroupInvitationsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_GroupInvitationsWithVersion); ok {
			return x.GroupInvitationsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetGroupJoinQuestionAnswerResult() *GroupJoinQuestionsAnswerResult {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_GroupJoinQuestionAnswerResult); ok {
			return x.GroupJoinQuestionAnswerResult
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetGroupJoinRequestsWithVersion() *GroupJoinRequestsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_GroupJoinRequestsWithVersion); ok {
			return x.GroupJoinRequestsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetGroupJoinQuestionsWithVersion() *GroupJoinQuestionsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_GroupJoinQuestionsWithVersion); ok {
			return x.GroupJoinQuestionsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetGroupMembersWithVersion() *GroupMembersWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_GroupMembersWithVersion); ok {
			return x.GroupMembersWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetGroupsWithVersion() *GroupsWithVersion {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_GroupsWithVersion); ok {
			return x.GroupsWithVersion
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetMeetings() *Meetings {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_Meetings); ok {
			return x.Meetings
		}
	}
	return nil
}

func (x *TurmsNotification_Data) GetStorageResourceInfos() *StorageResourceInfos {
	if x != nil {
		if x, ok := x.Kind.(*TurmsNotification_Data_StorageResourceInfos); ok {
			return x.StorageResourceInfos
		}
	}
	return nil
}

type isTurmsNotification_Data_Kind interface {
	isTurmsNotification_Data_Kind()
}

type TurmsNotification_Data_Long struct {
	// Common
	Long int64 `protobuf:"varint,1,opt,name=long,proto3,oneof"`
}

type TurmsNotification_Data_String_ struct {
	String_ string `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

type TurmsNotification_Data_LongsWithVersion struct {
	LongsWithVersion *LongsWithVersion `protobuf:"bytes,3,opt,name=longs_with_version,json=longsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_StringsWithVersion struct {
	StringsWithVersion *StringsWithVersion `protobuf:"bytes,4,opt,name=strings_with_version,json=stringsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_Conversations struct {
	// Conversation
	Conversations *Conversations `protobuf:"bytes,5,opt,name=conversations,proto3,oneof"`
}

type TurmsNotification_Data_Messages struct {
	// Message
	Messages *Messages `protobuf:"bytes,6,opt,name=messages,proto3,oneof"`
}

type TurmsNotification_Data_MessagesWithTotalList struct {
	MessagesWithTotalList *MessagesWithTotalList `protobuf:"bytes,7,opt,name=messages_with_total_list,json=messagesWithTotalList,proto3,oneof"`
}

type TurmsNotification_Data_UserSession struct {
	// User
	UserSession *UserSession `protobuf:"bytes,8,opt,name=user_session,json=userSession,proto3,oneof"`
}

type TurmsNotification_Data_UserInfosWithVersion struct {
	UserInfosWithVersion *UserInfosWithVersion `protobuf:"bytes,9,opt,name=user_infos_with_version,json=userInfosWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_UserOnlineStatuses struct {
	UserOnlineStatuses *UserOnlineStatuses `protobuf:"bytes,10,opt,name=user_online_statuses,json=userOnlineStatuses,proto3,oneof"`
}

type TurmsNotification_Data_UserFriendRequestsWithVersion struct {
	UserFriendRequestsWithVersion *UserFriendRequestsWithVersion `protobuf:"bytes,11,opt,name=user_friend_requests_with_version,json=userFriendRequestsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_UserRelationshipGroupsWithVersion struct {
	UserRelationshipGroupsWithVersion *UserRelationshipGroupsWithVersion `protobuf:"bytes,12,opt,name=user_relationship_groups_with_version,json=userRelationshipGroupsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_UserRelationshipsWithVersion struct {
	UserRelationshipsWithVersion *UserRelationshipsWithVersion `protobuf:"bytes,13,opt,name=user_relationships_with_version,json=userRelationshipsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_NearbyUsers struct {
	NearbyUsers *NearbyUsers `protobuf:"bytes,14,opt,name=nearby_users,json=nearbyUsers,proto3,oneof"`
}

type TurmsNotification_Data_GroupInvitationsWithVersion struct {
	// Group
	GroupInvitationsWithVersion *GroupInvitationsWithVersion `protobuf:"bytes,15,opt,name=group_invitations_with_version,json=groupInvitationsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_GroupJoinQuestionAnswerResult struct {
	GroupJoinQuestionAnswerResult *GroupJoinQuestionsAnswerResult `protobuf:"bytes,16,opt,name=group_join_question_answer_result,json=groupJoinQuestionAnswerResult,proto3,oneof"`
}

type TurmsNotification_Data_GroupJoinRequestsWithVersion struct {
	GroupJoinRequestsWithVersion *GroupJoinRequestsWithVersion `protobuf:"bytes,17,opt,name=group_join_requests_with_version,json=groupJoinRequestsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_GroupJoinQuestionsWithVersion struct {
	GroupJoinQuestionsWithVersion *GroupJoinQuestionsWithVersion `protobuf:"bytes,18,opt,name=group_join_questions_with_version,json=groupJoinQuestionsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_GroupMembersWithVersion struct {
	GroupMembersWithVersion *GroupMembersWithVersion `protobuf:"bytes,19,opt,name=group_members_with_version,json=groupMembersWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_GroupsWithVersion struct {
	GroupsWithVersion *GroupsWithVersion `protobuf:"bytes,20,opt,name=groups_with_version,json=groupsWithVersion,proto3,oneof"`
}

type TurmsNotification_Data_Meetings struct {
	// Conference
	Meetings *Meetings `protobuf:"bytes,40,opt,name=meetings,proto3,oneof"`
}

type TurmsNotification_Data_StorageResourceInfos struct {
	// Storage
	StorageResourceInfos *StorageResourceInfos `protobuf:"bytes,50,opt,name=storage_resource_infos,json=storageResourceInfos,proto3,oneof"`
}

func (*TurmsNotification_Data_Long) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_String_) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_LongsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_StringsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_Conversations) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_Messages) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_MessagesWithTotalList) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_UserSession) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_UserInfosWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_UserOnlineStatuses) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_UserFriendRequestsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_UserRelationshipGroupsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_UserRelationshipsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_NearbyUsers) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_GroupInvitationsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_GroupJoinQuestionAnswerResult) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_GroupJoinRequestsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_GroupJoinQuestionsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_GroupMembersWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_GroupsWithVersion) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_Meetings) isTurmsNotification_Data_Kind() {}

func (*TurmsNotification_Data_StorageResourceInfos) isTurmsNotification_Data_Kind() {}

var File_notification_turms_notification_proto protoreflect.FileDescriptor

const file_notification_turms_notification_proto_rawDesc = "" +
	"\n" +
	"%notification/turms_notification.proto\x12\x0eim.turms.proto\x1a\x1brequest/turms_request.proto\x1a%model/common/longs_with_version.proto\x1a'model/common/strings_with_version.proto\x1a0model/group/group_invitations_with_version.proto\x1a4model/group/group_join_questions_answer_result.proto\x1a3model/group/group_join_questions_with_version.proto\x1a2model/group/group_join_requests_with_version.proto\x1a,model/group/group_members_with_version.proto\x1a%model/group/groups_with_version.proto\x1a&model/conversation/conversations.proto\x1a\x1cmodel/message/messages.proto\x1a,model/message/messages_with_total_list.proto\x1a*model/storage/storage_resource_infos.proto\x1a\x1dmodel/user/nearby_users.proto\x1a2model/user/user_friend_requests_with_version.proto\x1a(model/user/user_infos_with_version.proto\x1a%model/user/user_online_statuses.proto\x1a6model/user/user_relationship_groups_with_version.proto\x1a0model/user/user_relationships_with_version.proto\x1a\x1dmodel/user/user_session.proto\x1a\x1fmodel/conference/meetings.proto\"\xda\x12\n" +
	"\x11TurmsNotification\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\"\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03H\x00R\trequestId\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x05 \x01(\x05H\x01R\x04code\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x06 \x01(\tH\x02R\x06reason\x88\x01\x01\x12:\n" +
	"\x04data\x18\a \x01(\v2&.im.turms.proto.TurmsNotification.DataR\x04data\x12&\n" +
	"\frequester_id\x18\n" +
	" \x01(\x03H\x03R\vrequesterId\x88\x01\x01\x12&\n" +
	"\fclose_status\x18\v \x01(\x05H\x04R\vcloseStatus\x88\x01\x01\x12E\n" +
	"\x0frelayed_request\x18\f \x01(\v2\x1c.im.turms.proto.TurmsRequestR\x0erelayedRequest\x1a\xb4\x0f\n" +
	"\x04Data\x12\x14\n" +
	"\x04long\x18\x01 \x01(\x03H\x00R\x04long\x12\x18\n" +
	"\x06string\x18\x02 \x01(\tH\x00R\x06string\x12P\n" +
	"\x12longs_with_version\x18\x03 \x01(\v2 .im.turms.proto.LongsWithVersionH\x00R\x10longsWithVersion\x12V\n" +
	"\x14strings_with_version\x18\x04 \x01(\v2\".im.turms.proto.StringsWithVersionH\x00R\x12stringsWithVersion\x12E\n" +
	"\rconversations\x18\x05 \x01(\v2\x1d.im.turms.proto.ConversationsH\x00R\rconversations\x126\n" +
	"\bmessages\x18\x06 \x01(\v2\x18.im.turms.proto.MessagesH\x00R\bmessages\x12`\n" +
	"\x18messages_with_total_list\x18\a \x01(\v2%.im.turms.proto.MessagesWithTotalListH\x00R\x15messagesWithTotalList\x12@\n" +
	"\fuser_session\x18\b \x01(\v2\x1b.im.turms.proto.UserSessionH\x00R\vuserSession\x12]\n" +
	"\x17user_infos_with_version\x18\t \x01(\v2$.im.turms.proto.UserInfosWithVersionH\x00R\x14userInfosWithVersion\x12V\n" +
	"\x14user_online_statuses\x18\n" +
	" \x01(\v2\".im.turms.proto.UserOnlineStatusesH\x00R\x12userOnlineStatuses\x12y\n" +
	"!user_friend_requests_with_version\x18\v \x01(\v2-.im.turms.proto.UserFriendRequestsWithVersionH\x00R\x1duserFriendRequestsWithVersion\x12\x85\x01\n" +
	"%user_relationship_groups_with_version\x18\f \x01(\v21.im.turms.proto.UserRelationshipGroupsWithVersionH\x00R!userRelationshipGroupsWithVersion\x12u\n" +
	"\x1fuser_relationships_with_version\x18\r \x01(\v2,.im.turms.proto.UserRelationshipsWithVersionH\x00R\x1cuserRelationshipsWithVersion\x12@\n" +
	"\fnearby_users\x18\x0e \x01(\v2\x1b.im.turms.proto.NearbyUsersH\x00R\vnearbyUsers\x12r\n" +
	"\x1egroup_invitations_with_version\x18\x0f \x01(\v2+.im.turms.proto.GroupInvitationsWithVersionH\x00R\x1bgroupInvitationsWithVersion\x12z\n" +
	"!group_join_question_answer_result\x18\x10 \x01(\v2..im.turms.proto.GroupJoinQuestionsAnswerResultH\x00R\x1dgroupJoinQuestionAnswerResult\x12v\n" +
	" group_join_requests_with_version\x18\x11 \x01(\v2,.im.turms.proto.GroupJoinRequestsWithVersionH\x00R\x1cgroupJoinRequestsWithVersion\x12y\n" +
	"!group_join_questions_with_version\x18\x12 \x01(\v2-.im.turms.proto.GroupJoinQuestionsWithVersionH\x00R\x1dgroupJoinQuestionsWithVersion\x12f\n" +
	"\x1agroup_members_with_version\x18\x13 \x01(\v2'.im.turms.proto.GroupMembersWithVersionH\x00R\x17groupMembersWithVersion\x12S\n" +
	"\x13groups_with_version\x18\x14 \x01(\v2!.im.turms.proto.GroupsWithVersionH\x00R\x11groupsWithVersion\x126\n" +
	"\bmeetings\x18( \x01(\v2\x18.im.turms.proto.MeetingsH\x00R\bmeetings\x12\\\n" +
	"\x16storage_resource_infos\x182 \x01(\v2$.im.turms.proto.StorageResourceInfosH\x00R\x14storageResourceInfosB\x06\n" +
	"\x04kindB\r\n" +
	"\v_request_idB\a\n" +
	"\x05_codeB\t\n" +
	"\a_reasonB\x0f\n" +
	"\r_requester_idB\x0f\n" +
	"\r_close_statusBZ\n" +
	"5im.turms.server.common.access.client.dto.notificationP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_notification_turms_notification_proto_rawDescOnce sync.Once
	file_notification_turms_notification_proto_rawDescData []byte
)

func file_notification_turms_notification_proto_rawDescGZIP() []byte {
	file_notification_turms_notification_proto_rawDescOnce.Do(func() {
		file_notification_turms_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_turms_notification_proto_rawDesc), len(file_notification_turms_notification_proto_rawDesc)))
	})
	return file_notification_turms_notification_proto_rawDescData
}

var file_notification_turms_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_turms_notification_proto_goTypes = []any{
	(*TurmsNotification)(nil),                 // 0: im.turms.proto.TurmsNotification
	(*TurmsNotification_Data)(nil),            // 1: im.turms.proto.TurmsNotification.Data
	(*TurmsRequest)(nil),                      // 2: im.turms.proto.TurmsRequest
	(*LongsWithVersion)(nil),                  // 3: im.turms.proto.LongsWithVersion
	(*StringsWithVersion)(nil),                // 4: im.turms.proto.StringsWithVersion
	(*Conversations)(nil),                     // 5: im.turms.proto.Conversations
	(*Messages)(nil),                          // 6: im.turms.proto.Messages
	(*MessagesWithTotalList)(nil),             // 7: im.turms.proto.MessagesWithTotalList
	(*UserSession)(nil),                       // 8: im.turms.proto.UserSession
	(*UserInfosWithVersion)(nil),              // 9: im.turms.proto.UserInfosWithVersion
	(*UserOnlineStatuses)(nil),                // 10: im.turms.proto.UserOnlineStatuses
	(*UserFriendRequestsWithVersion)(nil),     // 11: im.turms.proto.UserFriendRequestsWithVersion
	(*UserRelationshipGroupsWithVersion)(nil), // 12: im.turms.proto.UserRelationshipGroupsWithVersion
	(*UserRelationshipsWithVersion)(nil),      // 13: im.turms.proto.UserRelationshipsWithVersion
	(*NearbyUsers)(nil),                       // 14: im.turms.proto.NearbyUsers
	(*GroupInvitationsWithVersion)(nil),       // 15: im.turms.proto.GroupInvitationsWithVersion
	(*GroupJoinQuestionsAnswerResult)(nil),    // 16: im.turms.proto.GroupJoinQuestionsAnswerResult
	(*GroupJoinRequestsWithVersion)(nil),      // 17: im.turms.proto.GroupJoinRequestsWithVersion
	(*GroupJoinQuestionsWithVersion)(nil),     // 18: im.turms.proto.GroupJoinQuestionsWithVersion
	(*GroupMembersWithVersion)(nil),           // 19: im.turms.proto.GroupMembersWithVersion
	(*GroupsWithVersion)(nil),                 // 20: im.turms.proto.GroupsWithVersion
	(*Meetings)(nil),                          // 21: im.turms.proto.Meetings
	(*StorageResourceInfos)(nil),              // 22: im.turms.proto.StorageResourceInfos
}
var file_notification_turms_notification_proto_depIdxs = []int32{
	1,  // 0: im.turms.proto.TurmsNotification.data:type_name -> im.turms.proto.TurmsNotification.Data
	2,  // 1: im.turms.proto.TurmsNotification.relayed_request:type_name -> im.turms.proto.TurmsRequest
	3,  // 2: im.turms.proto.TurmsNotification.Data.longs_with_version:type_name -> im.turms.proto.LongsWithVersion
	4,  // 3: im.turms.proto.TurmsNotification.Data.strings_with_version:type_name -> im.turms.proto.StringsWithVersion
	5,  // 4: im.turms.proto.TurmsNotification.Data.conversations:type_name -> im.turms.proto.Conversations
	6,  // 5: im.turms.proto.TurmsNotification.Data.messages:type_name -> im.turms.proto.Messages
	7,  // 6: im.turms.proto.TurmsNotification.Data.messages_with_total_list:type_name -> im.turms.proto.MessagesWithTotalList
	8,  // 7: im.turms.proto.TurmsNotification.Data.user_session:type_name -> im.turms.proto.UserSession
	9,  // 8: im.turms.proto.TurmsNotification.Data.user_infos_with_version:type_name -> im.turms.proto.UserInfosWithVersion
	10, // 9: im.turms.proto.TurmsNotification.Data.user_online_statuses:type_name -> im.turms.proto.UserOnlineStatuses
	11, // 10: im.turms.proto.TurmsNotification.Data.user_friend_requests_with_version:type_name -> im.turms.proto.UserFriendRequestsWithVersion
	12, // 11: im.turms.proto.TurmsNotification.Data.user_relationship_groups_with_version:type_name -> im.turms.proto.UserRelationshipGroupsWithVersion
	13, // 12: im.turms.proto.TurmsNotification.Data.user_relationships_with_version:type_name -> im.turms.proto.UserRelationshipsWithVersion
	14, // 13: im.turms.proto.TurmsNotification.Data.nearby_users:type_name -> im.turms.proto.NearbyUsers
	15, // 14: im.turms.proto.TurmsNotification.Data.group_invitations_with_version:type_name -> im.turms.proto.GroupInvitationsWithVersion
	16, // 15: im.turms.proto.TurmsNotification.Data.group_join_question_answer_result:type_name -> im.turms.proto.GroupJoinQuestionsAnswerResult
	17, // 16: im.turms.proto.TurmsNotification.Data.group_join_requests_with_version:type_name -> im.turms.proto.GroupJoinRequestsWithVersion
	18, // 17: im.turms.proto.TurmsNotification.Data.group_join_questions_with_version:type_name -> im.turms.proto.GroupJoinQuestionsWithVersion
	19, // 18: im.turms.proto.TurmsNotification.Data.group_members_with_version:type_name -> im.turms.proto.GroupMembersWithVersion
	20, // 19: im.turms.proto.TurmsNotification.Data.groups_with_version:type_name -> im.turms.proto.GroupsWithVersion
	21, // 20: im.turms.proto.TurmsNotification.Data.meetings:type_name -> im.turms.proto.Meetings
	22, // 21: im.turms.proto.TurmsNotification.Data.storage_resource_infos:type_name -> im.turms.proto.StorageResourceInfos
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_notification_turms_notification_proto_init() }
func file_notification_turms_notification_proto_init() {
	if File_notification_turms_notification_proto != nil {
		return
	}
	file_request_turms_request_proto_init()
	file_model_common_longs_with_version_proto_init()
	file_model_common_strings_with_version_proto_init()
	file_model_group_group_invitations_with_version_proto_init()
	file_model_group_group_join_questions_answer_result_proto_init()
	file_model_group_group_join_questions_with_version_proto_init()
	file_model_group_group_join_requests_with_version_proto_init()
	file_model_group_group_members_with_version_proto_init()
	file_model_group_groups_with_version_proto_init()
	file_model_conversation_conversations_proto_init()
	file_model_message_messages_proto_init()
	file_model_message_messages_with_total_list_proto_init()
	file_model_storage_storage_resource_infos_proto_init()
	file_model_user_nearby_users_proto_init()
	file_model_user_user_friend_requests_with_version_proto_init()
	file_model_user_user_infos_with_version_proto_init()
	file_model_user_user_online_statuses_proto_init()
	file_model_user_user_relationship_groups_with_version_proto_init()
	file_model_user_user_relationships_with_version_proto_init()
	file_model_user_user_session_proto_init()
	file_model_conference_meetings_proto_init()
	file_notification_turms_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_notification_turms_notification_proto_msgTypes[1].OneofWrappers = []any{
		(*TurmsNotification_Data_Long)(nil),
		(*TurmsNotification_Data_String_)(nil),
		(*TurmsNotification_Data_LongsWithVersion)(nil),
		(*TurmsNotification_Data_StringsWithVersion)(nil),
		(*TurmsNotification_Data_Conversations)(nil),
		(*TurmsNotification_Data_Messages)(nil),
		(*TurmsNotification_Data_MessagesWithTotalList)(nil),
		(*TurmsNotification_Data_UserSession)(nil),
		(*TurmsNotification_Data_UserInfosWithVersion)(nil),
		(*TurmsNotification_Data_UserOnlineStatuses)(nil),
		(*TurmsNotification_Data_UserFriendRequestsWithVersion)(nil),
		(*TurmsNotification_Data_UserRelationshipGroupsWithVersion)(nil),
		(*TurmsNotification_Data_UserRelationshipsWithVersion)(nil),
		(*TurmsNotification_Data_NearbyUsers)(nil),
		(*TurmsNotification_Data_GroupInvitationsWithVersion)(nil),
		(*TurmsNotification_Data_GroupJoinQuestionAnswerResult)(nil),
		(*TurmsNotification_Data_GroupJoinRequestsWithVersion)(nil),
		(*TurmsNotification_Data_GroupJoinQuestionsWithVersion)(nil),
		(*TurmsNotification_Data_GroupMembersWithVersion)(nil),
		(*TurmsNotification_Data_GroupsWithVersion)(nil),
		(*TurmsNotification_Data_Meetings)(nil),
		(*TurmsNotification_Data_StorageResourceInfos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_turms_notification_proto_rawDesc), len(file_notification_turms_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_turms_notification_proto_goTypes,
		DependencyIndexes: file_notification_turms_notification_proto_depIdxs,
		MessageInfos:      file_notification_turms_notification_proto_msgTypes,
	}.Build()
	File_notification_turms_notification_proto = out.File
	file_notification_turms_notification_proto_goTypes = nil
	file_notification_turms_notification_proto_depIdxs = nil
}
