// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/update_user_online_status_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserOnlineStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query filter
	DeviceTypes []DeviceType `protobuf:"varint,1,rep,packed,name=device_types,json=deviceTypes,proto3,enum=im.turms.proto.DeviceType" json:"device_types,omitempty"`
	// Update
	UserStatus    UserStatus `protobuf:"varint,2,opt,name=user_status,json=userStatus,proto3,enum=im.turms.proto.UserStatus" json:"user_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserOnlineStatusRequest) Reset() {
	*x = UpdateUserOnlineStatusRequest{}
	mi := &file_request_user_update_user_online_status_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserOnlineStatusRequest) ProtoMessage() {}

func (x *UpdateUserOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_update_user_online_status_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_request_user_update_user_online_status_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserOnlineStatusRequest) GetDeviceTypes() []DeviceType {
	if x != nil {
		return x.DeviceTypes
	}
	return nil
}

func (x *UpdateUserOnlineStatusRequest) GetUserStatus() UserStatus {
	if x != nil {
		return x.UserStatus
	}
	return UserStatus_AVAILABLE
}

var File_request_user_update_user_online_status_request_proto protoreflect.FileDescriptor

const file_request_user_update_user_online_status_request_proto_rawDesc = "" +
	"\n" +
	"4request/user/update_user_online_status_request.proto\x12\x0eim.turms.proto\x1a\x1aconstant/user_status.proto\x1a\x1aconstant/device_type.proto\"\x9b\x01\n" +
	"\x1dUpdateUserOnlineStatusRequest\x12=\n" +
	"\fdevice_types\x18\x01 \x03(\x0e2\x1a.im.turms.proto.DeviceTypeR\vdeviceTypes\x12;\n" +
	"\vuser_status\x18\x02 \x01(\x0e2\x1a.im.turms.proto.UserStatusR\n" +
	"userStatusBZ\n" +
	"5im.turms.server.common.access.client.dto.request.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_update_user_online_status_request_proto_rawDescOnce sync.Once
	file_request_user_update_user_online_status_request_proto_rawDescData []byte
)

func file_request_user_update_user_online_status_request_proto_rawDescGZIP() []byte {
	file_request_user_update_user_online_status_request_proto_rawDescOnce.Do(func() {
		file_request_user_update_user_online_status_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_update_user_online_status_request_proto_rawDesc), len(file_request_user_update_user_online_status_request_proto_rawDesc)))
	})
	return file_request_user_update_user_online_status_request_proto_rawDescData
}

var file_request_user_update_user_online_status_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_user_update_user_online_status_request_proto_goTypes = []any{
	(*UpdateUserOnlineStatusRequest)(nil), // 0: im.turms.proto.UpdateUserOnlineStatusRequest
	(DeviceType)(0),                       // 1: im.turms.proto.DeviceType
	(UserStatus)(0),                       // 2: im.turms.proto.UserStatus
}
var file_request_user_update_user_online_status_request_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.UpdateUserOnlineStatusRequest.device_types:type_name -> im.turms.proto.DeviceType
	2, // 1: im.turms.proto.UpdateUserOnlineStatusRequest.user_status:type_name -> im.turms.proto.UserStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_user_update_user_online_status_request_proto_init() }
func file_request_user_update_user_online_status_request_proto_init() {
	if File_request_user_update_user_online_status_request_proto != nil {
		return
	}
	file_constant_user_status_proto_init()
	file_constant_device_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_update_user_online_status_request_proto_rawDesc), len(file_request_user_update_user_online_status_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_update_user_online_status_request_proto_goTypes,
		DependencyIndexes: file_request_user_update_user_online_status_request_proto_depIdxs,
		MessageInfos:      file_request_user_update_user_online_status_request_proto_msgTypes,
	}.Build()
	File_request_user_update_user_online_status_request_proto = out.File
	file_request_user_update_user_online_status_request_proto_goTypes = nil
	file_request_user_update_user_online_status_request_proto_depIdxs = nil
}
