// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/update_user_location_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update
	Latitude      float32           `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32           `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Details       map[string]string `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserLocationRequest) Reset() {
	*x = UpdateUserLocationRequest{}
	mi := &file_request_user_update_user_location_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserLocationRequest) ProtoMessage() {}

func (x *UpdateUserLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_update_user_location_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserLocationRequest) Descriptor() ([]byte, []int) {
	return file_request_user_update_user_location_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserLocationRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateUserLocationRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateUserLocationRequest) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_request_user_update_user_location_request_proto protoreflect.FileDescriptor

const file_request_user_update_user_location_request_proto_rawDesc = "" +
	"\n" +
	"/request/user/update_user_location_request.proto\x12\x0eim.turms.proto\"\xe3\x01\n" +
	"\x19UpdateUserLocationRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12P\n" +
	"\adetails\x18\x03 \x03(\v26.im.turms.proto.UpdateUserLocationRequest.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BZ\n" +
	"5im.turms.server.common.access.client.dto.request.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_update_user_location_request_proto_rawDescOnce sync.Once
	file_request_user_update_user_location_request_proto_rawDescData []byte
)

func file_request_user_update_user_location_request_proto_rawDescGZIP() []byte {
	file_request_user_update_user_location_request_proto_rawDescOnce.Do(func() {
		file_request_user_update_user_location_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_update_user_location_request_proto_rawDesc), len(file_request_user_update_user_location_request_proto_rawDesc)))
	})
	return file_request_user_update_user_location_request_proto_rawDescData
}

var file_request_user_update_user_location_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_request_user_update_user_location_request_proto_goTypes = []any{
	(*UpdateUserLocationRequest)(nil), // 0: im.turms.proto.UpdateUserLocationRequest
	nil,                               // 1: im.turms.proto.UpdateUserLocationRequest.DetailsEntry
}
var file_request_user_update_user_location_request_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.UpdateUserLocationRequest.details:type_name -> im.turms.proto.UpdateUserLocationRequest.DetailsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_user_update_user_location_request_proto_init() }
func file_request_user_update_user_location_request_proto_init() {
	if File_request_user_update_user_location_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_update_user_location_request_proto_rawDesc), len(file_request_user_update_user_location_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_update_user_location_request_proto_goTypes,
		DependencyIndexes: file_request_user_update_user_location_request_proto_depIdxs,
		MessageInfos:      file_request_user_update_user_location_request_proto_msgTypes,
	}.Build()
	File_request_user_update_user_location_request_proto = out.File
	file_request_user_update_user_location_request_proto_goTypes = nil
	file_request_user_update_user_location_request_proto_depIdxs = nil
}
