// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/user/update_user_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update
	Password              *string                `protobuf:"bytes,1,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Name                  *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Intro                 *string                `protobuf:"bytes,3,opt,name=intro,proto3,oneof" json:"intro,omitempty"`
	ProfilePicture        *string                `protobuf:"bytes,4,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
	ProfileAccessStrategy *ProfileAccessStrategy `protobuf:"varint,5,opt,name=profile_access_strategy,json=profileAccessStrategy,proto3,enum=im.turms.proto.ProfileAccessStrategy,oneof" json:"profile_access_strategy,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_request_user_update_user_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_user_update_user_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_request_user_update_user_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateUserRequest) GetIntro() string {
	if x != nil && x.Intro != nil {
		return *x.Intro
	}
	return ""
}

func (x *UpdateUserRequest) GetProfilePicture() string {
	if x != nil && x.ProfilePicture != nil {
		return *x.ProfilePicture
	}
	return ""
}

func (x *UpdateUserRequest) GetProfileAccessStrategy() ProfileAccessStrategy {
	if x != nil && x.ProfileAccessStrategy != nil {
		return *x.ProfileAccessStrategy
	}
	return ProfileAccessStrategy_ALL
}

var File_request_user_update_user_request_proto protoreflect.FileDescriptor

const file_request_user_update_user_request_proto_rawDesc = "" +
	"\n" +
	"&request/user/update_user_request.proto\x12\x0eim.turms.proto\x1a&constant/profile_access_strategy.proto\"\xca\x02\n" +
	"\x11UpdateUserRequest\x12\x1f\n" +
	"\bpassword\x18\x01 \x01(\tH\x00R\bpassword\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05intro\x18\x03 \x01(\tH\x02R\x05intro\x88\x01\x01\x12,\n" +
	"\x0fprofile_picture\x18\x04 \x01(\tH\x03R\x0eprofilePicture\x88\x01\x01\x12b\n" +
	"\x17profile_access_strategy\x18\x05 \x01(\x0e2%.im.turms.proto.ProfileAccessStrategyH\x04R\x15profileAccessStrategy\x88\x01\x01B\v\n" +
	"\t_passwordB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_introB\x12\n" +
	"\x10_profile_pictureB\x1a\n" +
	"\x18_profile_access_strategyBZ\n" +
	"5im.turms.server.common.access.client.dto.request.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_user_update_user_request_proto_rawDescOnce sync.Once
	file_request_user_update_user_request_proto_rawDescData []byte
)

func file_request_user_update_user_request_proto_rawDescGZIP() []byte {
	file_request_user_update_user_request_proto_rawDescOnce.Do(func() {
		file_request_user_update_user_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_user_update_user_request_proto_rawDesc), len(file_request_user_update_user_request_proto_rawDesc)))
	})
	return file_request_user_update_user_request_proto_rawDescData
}

var file_request_user_update_user_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_user_update_user_request_proto_goTypes = []any{
	(*UpdateUserRequest)(nil),  // 0: im.turms.proto.UpdateUserRequest
	(ProfileAccessStrategy)(0), // 1: im.turms.proto.ProfileAccessStrategy
}
var file_request_user_update_user_request_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.UpdateUserRequest.profile_access_strategy:type_name -> im.turms.proto.ProfileAccessStrategy
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_user_update_user_request_proto_init() }
func file_request_user_update_user_request_proto_init() {
	if File_request_user_update_user_request_proto != nil {
		return
	}
	file_constant_profile_access_strategy_proto_init()
	file_request_user_update_user_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_user_update_user_request_proto_rawDesc), len(file_request_user_update_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_user_update_user_request_proto_goTypes,
		DependencyIndexes: file_request_user_update_user_request_proto_depIdxs,
		MessageInfos:      file_request_user_update_user_request_proto_msgTypes,
	}.Build()
	File_request_user_update_user_request_proto = out.File
	file_request_user_update_user_request_proto_goTypes = nil
	file_request_user_update_user_request_proto_depIdxs = nil
}
