// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/storage/update_message_attachment_info_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMessageAttachmentInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query filter
	AttachmentIdNum *int64  `protobuf:"varint,1,opt,name=attachment_id_num,json=attachmentIdNum,proto3,oneof" json:"attachment_id_num,omitempty"`
	AttachmentIdStr *string `protobuf:"bytes,2,opt,name=attachment_id_str,json=attachmentIdStr,proto3,oneof" json:"attachment_id_str,omitempty"`
	// Update
	UserIdToShareWith    *int64 `protobuf:"varint,3,opt,name=user_id_to_share_with,json=userIdToShareWith,proto3,oneof" json:"user_id_to_share_with,omitempty"`
	UserIdToUnshareWith  *int64 `protobuf:"varint,4,opt,name=user_id_to_unshare_with,json=userIdToUnshareWith,proto3,oneof" json:"user_id_to_unshare_with,omitempty"`
	GroupIdToShareWith   *int64 `protobuf:"varint,5,opt,name=group_id_to_share_with,json=groupIdToShareWith,proto3,oneof" json:"group_id_to_share_with,omitempty"`
	GroupIdToUnshareWith *int64 `protobuf:"varint,6,opt,name=group_id_to_unshare_with,json=groupIdToUnshareWith,proto3,oneof" json:"group_id_to_unshare_with,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateMessageAttachmentInfoRequest) Reset() {
	*x = UpdateMessageAttachmentInfoRequest{}
	mi := &file_request_storage_update_message_attachment_info_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageAttachmentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageAttachmentInfoRequest) ProtoMessage() {}

func (x *UpdateMessageAttachmentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_storage_update_message_attachment_info_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageAttachmentInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageAttachmentInfoRequest) Descriptor() ([]byte, []int) {
	return file_request_storage_update_message_attachment_info_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMessageAttachmentInfoRequest) GetAttachmentIdNum() int64 {
	if x != nil && x.AttachmentIdNum != nil {
		return *x.AttachmentIdNum
	}
	return 0
}

func (x *UpdateMessageAttachmentInfoRequest) GetAttachmentIdStr() string {
	if x != nil && x.AttachmentIdStr != nil {
		return *x.AttachmentIdStr
	}
	return ""
}

func (x *UpdateMessageAttachmentInfoRequest) GetUserIdToShareWith() int64 {
	if x != nil && x.UserIdToShareWith != nil {
		return *x.UserIdToShareWith
	}
	return 0
}

func (x *UpdateMessageAttachmentInfoRequest) GetUserIdToUnshareWith() int64 {
	if x != nil && x.UserIdToUnshareWith != nil {
		return *x.UserIdToUnshareWith
	}
	return 0
}

func (x *UpdateMessageAttachmentInfoRequest) GetGroupIdToShareWith() int64 {
	if x != nil && x.GroupIdToShareWith != nil {
		return *x.GroupIdToShareWith
	}
	return 0
}

func (x *UpdateMessageAttachmentInfoRequest) GetGroupIdToUnshareWith() int64 {
	if x != nil && x.GroupIdToUnshareWith != nil {
		return *x.GroupIdToUnshareWith
	}
	return 0
}

var File_request_storage_update_message_attachment_info_request_proto protoreflect.FileDescriptor

const file_request_storage_update_message_attachment_info_request_proto_rawDesc = "" +
	"\n" +
	"<request/storage/update_message_attachment_info_request.proto\x12\x0eim.turms.proto\"\x88\x04\n" +
	"\"UpdateMessageAttachmentInfoRequest\x12/\n" +
	"\x11attachment_id_num\x18\x01 \x01(\x03H\x00R\x0fattachmentIdNum\x88\x01\x01\x12/\n" +
	"\x11attachment_id_str\x18\x02 \x01(\tH\x01R\x0fattachmentIdStr\x88\x01\x01\x125\n" +
	"\x15user_id_to_share_with\x18\x03 \x01(\x03H\x02R\x11userIdToShareWith\x88\x01\x01\x129\n" +
	"\x17user_id_to_unshare_with\x18\x04 \x01(\x03H\x03R\x13userIdToUnshareWith\x88\x01\x01\x127\n" +
	"\x16group_id_to_share_with\x18\x05 \x01(\x03H\x04R\x12groupIdToShareWith\x88\x01\x01\x12;\n" +
	"\x18group_id_to_unshare_with\x18\x06 \x01(\x03H\x05R\x14groupIdToUnshareWith\x88\x01\x01B\x14\n" +
	"\x12_attachment_id_numB\x14\n" +
	"\x12_attachment_id_strB\x18\n" +
	"\x16_user_id_to_share_withB\x1a\n" +
	"\x18_user_id_to_unshare_withB\x19\n" +
	"\x17_group_id_to_share_withB\x1b\n" +
	"\x19_group_id_to_unshare_withB]\n" +
	"8im.turms.server.common.access.client.dto.request.storageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_storage_update_message_attachment_info_request_proto_rawDescOnce sync.Once
	file_request_storage_update_message_attachment_info_request_proto_rawDescData []byte
)

func file_request_storage_update_message_attachment_info_request_proto_rawDescGZIP() []byte {
	file_request_storage_update_message_attachment_info_request_proto_rawDescOnce.Do(func() {
		file_request_storage_update_message_attachment_info_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_storage_update_message_attachment_info_request_proto_rawDesc), len(file_request_storage_update_message_attachment_info_request_proto_rawDesc)))
	})
	return file_request_storage_update_message_attachment_info_request_proto_rawDescData
}

var file_request_storage_update_message_attachment_info_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_storage_update_message_attachment_info_request_proto_goTypes = []any{
	(*UpdateMessageAttachmentInfoRequest)(nil), // 0: im.turms.proto.UpdateMessageAttachmentInfoRequest
}
var file_request_storage_update_message_attachment_info_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_storage_update_message_attachment_info_request_proto_init() }
func file_request_storage_update_message_attachment_info_request_proto_init() {
	if File_request_storage_update_message_attachment_info_request_proto != nil {
		return
	}
	file_request_storage_update_message_attachment_info_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_storage_update_message_attachment_info_request_proto_rawDesc), len(file_request_storage_update_message_attachment_info_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_storage_update_message_attachment_info_request_proto_goTypes,
		DependencyIndexes: file_request_storage_update_message_attachment_info_request_proto_depIdxs,
		MessageInfos:      file_request_storage_update_message_attachment_info_request_proto_msgTypes,
	}.Build()
	File_request_storage_update_message_attachment_info_request_proto = out.File
	file_request_storage_update_message_attachment_info_request_proto_goTypes = nil
	file_request_storage_update_message_attachment_info_request_proto_depIdxs = nil
}
