// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/update_group_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query filter
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Update options
	QuitAfterTransfer *bool `protobuf:"varint,2,opt,name=quit_after_transfer,json=quitAfterTransfer,proto3,oneof" json:"quit_after_transfer,omitempty"`
	// Update
	Name          *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Intro         *string `protobuf:"bytes,4,opt,name=intro,proto3,oneof" json:"intro,omitempty"`
	Announcement  *string `protobuf:"bytes,5,opt,name=announcement,proto3,oneof" json:"announcement,omitempty"`
	MinScore      *int32  `protobuf:"varint,6,opt,name=min_score,json=minScore,proto3,oneof" json:"min_score,omitempty"`
	TypeId        *int64  `protobuf:"varint,7,opt,name=type_id,json=typeId,proto3,oneof" json:"type_id,omitempty"`
	MuteEndDate   *int64  `protobuf:"varint,8,opt,name=mute_end_date,json=muteEndDate,proto3,oneof" json:"mute_end_date,omitempty"`
	SuccessorId   *int64  `protobuf:"varint,9,opt,name=successor_id,json=successorId,proto3,oneof" json:"successor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_request_group_update_group_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_update_group_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_request_group_update_group_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupRequest) GetQuitAfterTransfer() bool {
	if x != nil && x.QuitAfterTransfer != nil {
		return *x.QuitAfterTransfer
	}
	return false
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetIntro() string {
	if x != nil && x.Intro != nil {
		return *x.Intro
	}
	return ""
}

func (x *UpdateGroupRequest) GetAnnouncement() string {
	if x != nil && x.Announcement != nil {
		return *x.Announcement
	}
	return ""
}

func (x *UpdateGroupRequest) GetMinScore() int32 {
	if x != nil && x.MinScore != nil {
		return *x.MinScore
	}
	return 0
}

func (x *UpdateGroupRequest) GetTypeId() int64 {
	if x != nil && x.TypeId != nil {
		return *x.TypeId
	}
	return 0
}

func (x *UpdateGroupRequest) GetMuteEndDate() int64 {
	if x != nil && x.MuteEndDate != nil {
		return *x.MuteEndDate
	}
	return 0
}

func (x *UpdateGroupRequest) GetSuccessorId() int64 {
	if x != nil && x.SuccessorId != nil {
		return *x.SuccessorId
	}
	return 0
}

var File_request_group_update_group_request_proto protoreflect.FileDescriptor

const file_request_group_update_group_request_proto_rawDesc = "" +
	"\n" +
	"(request/group/update_group_request.proto\x12\x0eim.turms.proto\"\xcb\x03\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x123\n" +
	"\x13quit_after_transfer\x18\x02 \x01(\bH\x00R\x11quitAfterTransfer\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05intro\x18\x04 \x01(\tH\x02R\x05intro\x88\x01\x01\x12'\n" +
	"\fannouncement\x18\x05 \x01(\tH\x03R\fannouncement\x88\x01\x01\x12 \n" +
	"\tmin_score\x18\x06 \x01(\x05H\x04R\bminScore\x88\x01\x01\x12\x1c\n" +
	"\atype_id\x18\a \x01(\x03H\x05R\x06typeId\x88\x01\x01\x12'\n" +
	"\rmute_end_date\x18\b \x01(\x03H\x06R\vmuteEndDate\x88\x01\x01\x12&\n" +
	"\fsuccessor_id\x18\t \x01(\x03H\aR\vsuccessorId\x88\x01\x01B\x16\n" +
	"\x14_quit_after_transferB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_introB\x0f\n" +
	"\r_announcementB\f\n" +
	"\n" +
	"_min_scoreB\n" +
	"\n" +
	"\b_type_idB\x10\n" +
	"\x0e_mute_end_dateB\x0f\n" +
	"\r_successor_idB[\n" +
	"6im.turms.server.common.access.client.dto.request.groupP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_update_group_request_proto_rawDescOnce sync.Once
	file_request_group_update_group_request_proto_rawDescData []byte
)

func file_request_group_update_group_request_proto_rawDescGZIP() []byte {
	file_request_group_update_group_request_proto_rawDescOnce.Do(func() {
		file_request_group_update_group_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_update_group_request_proto_rawDesc), len(file_request_group_update_group_request_proto_rawDesc)))
	})
	return file_request_group_update_group_request_proto_rawDescData
}

var file_request_group_update_group_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_update_group_request_proto_goTypes = []any{
	(*UpdateGroupRequest)(nil), // 0: im.turms.proto.UpdateGroupRequest
}
var file_request_group_update_group_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_group_update_group_request_proto_init() }
func file_request_group_update_group_request_proto_init() {
	if File_request_group_update_group_request_proto != nil {
		return
	}
	file_request_group_update_group_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_update_group_request_proto_rawDesc), len(file_request_group_update_group_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_update_group_request_proto_goTypes,
		DependencyIndexes: file_request_group_update_group_request_proto_depIdxs,
		MessageInfos:      file_request_group_update_group_request_proto_msgTypes,
	}.Build()
	File_request_group_update_group_request_proto = out.File
	file_request_group_update_group_request_proto_goTypes = nil
	file_request_group_update_group_request_proto_depIdxs = nil
}
