// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/message/update_message_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query filter
	MessageId int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Update
	Text          *string  `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Records       [][]byte `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	RecallDate    *int64   `protobuf:"varint,4,opt,name=recall_date,json=recallDate,proto3,oneof" json:"recall_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_request_message_update_message_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_message_update_message_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_request_message_update_message_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *UpdateMessageRequest) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *UpdateMessageRequest) GetRecallDate() int64 {
	if x != nil && x.RecallDate != nil {
		return *x.RecallDate
	}
	return 0
}

var File_request_message_update_message_request_proto protoreflect.FileDescriptor

const file_request_message_update_message_request_proto_rawDesc = "" +
	"\n" +
	",request/message/update_message_request.proto\x12\x0eim.turms.proto\"\xa7\x01\n" +
	"\x14UpdateMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x18\n" +
	"\arecords\x18\x03 \x03(\fR\arecords\x12$\n" +
	"\vrecall_date\x18\x04 \x01(\x03H\x01R\n" +
	"recallDate\x88\x01\x01B\a\n" +
	"\x05_textB\x0e\n" +
	"\f_recall_dateB]\n" +
	"8im.turms.server.common.access.client.dto.request.messageP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_message_update_message_request_proto_rawDescOnce sync.Once
	file_request_message_update_message_request_proto_rawDescData []byte
)

func file_request_message_update_message_request_proto_rawDescGZIP() []byte {
	file_request_message_update_message_request_proto_rawDescOnce.Do(func() {
		file_request_message_update_message_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_message_update_message_request_proto_rawDesc), len(file_request_message_update_message_request_proto_rawDesc)))
	})
	return file_request_message_update_message_request_proto_rawDescData
}

var file_request_message_update_message_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_message_update_message_request_proto_goTypes = []any{
	(*UpdateMessageRequest)(nil), // 0: im.turms.proto.UpdateMessageRequest
}
var file_request_message_update_message_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_message_update_message_request_proto_init() }
func file_request_message_update_message_request_proto_init() {
	if File_request_message_update_message_request_proto != nil {
		return
	}
	file_request_message_update_message_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_message_update_message_request_proto_rawDesc), len(file_request_message_update_message_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_message_update_message_request_proto_goTypes,
		DependencyIndexes: file_request_message_update_message_request_proto_depIdxs,
		MessageInfos:      file_request_message_update_message_request_proto_msgTypes,
	}.Build()
	File_request_message_update_message_request_proto = out.File
	file_request_message_update_message_request_proto_goTypes = nil
	file_request_message_update_message_request_proto_depIdxs = nil
}
