// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/conference/update_meeting_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Intro         *string                `protobuf:"bytes,3,opt,name=intro,proto3,oneof" json:"intro,omitempty"`
	Password      *string                `protobuf:"bytes,4,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMeetingRequest) Reset() {
	*x = UpdateMeetingRequest{}
	mi := &file_request_conference_update_meeting_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingRequest) ProtoMessage() {}

func (x *UpdateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_conference_update_meeting_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_request_conference_update_meeting_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMeetingRequest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UpdateMeetingRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateMeetingRequest) GetIntro() string {
	if x != nil && x.Intro != nil {
		return *x.Intro
	}
	return ""
}

func (x *UpdateMeetingRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

var File_request_conference_update_meeting_request_proto protoreflect.FileDescriptor

const file_request_conference_update_meeting_request_proto_rawDesc = "" +
	"\n" +
	"/request/conference/update_meeting_request.proto\x12\x0eim.turms.proto\"\xa7\x01\n" +
	"\x14UpdateMeetingRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05intro\x18\x03 \x01(\tH\x02R\x05intro\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x04 \x01(\tH\x03R\bpassword\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_introB\v\n" +
	"\t_passwordB]\n" +
	";im.turms.server.common.access.client.dto.request.conferenceP\x01Z\x1cim.turms/server/pkg/protocolb\x06proto3"

var (
	file_request_conference_update_meeting_request_proto_rawDescOnce sync.Once
	file_request_conference_update_meeting_request_proto_rawDescData []byte
)

func file_request_conference_update_meeting_request_proto_rawDescGZIP() []byte {
	file_request_conference_update_meeting_request_proto_rawDescOnce.Do(func() {
		file_request_conference_update_meeting_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_conference_update_meeting_request_proto_rawDesc), len(file_request_conference_update_meeting_request_proto_rawDesc)))
	})
	return file_request_conference_update_meeting_request_proto_rawDescData
}

var file_request_conference_update_meeting_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_conference_update_meeting_request_proto_goTypes = []any{
	(*UpdateMeetingRequest)(nil), // 0: im.turms.proto.UpdateMeetingRequest
}
var file_request_conference_update_meeting_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_conference_update_meeting_request_proto_init() }
func file_request_conference_update_meeting_request_proto_init() {
	if File_request_conference_update_meeting_request_proto != nil {
		return
	}
	file_request_conference_update_meeting_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_conference_update_meeting_request_proto_rawDesc), len(file_request_conference_update_meeting_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_conference_update_meeting_request_proto_goTypes,
		DependencyIndexes: file_request_conference_update_meeting_request_proto_depIdxs,
		MessageInfos:      file_request_conference_update_meeting_request_proto_msgTypes,
	}.Build()
	File_request_conference_update_meeting_request_proto = out.File
	file_request_conference_update_meeting_request_proto_goTypes = nil
	file_request_conference_update_meeting_request_proto_depIdxs = nil
}
