// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/group/enrollment/update_group_join_question_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateGroupJoinQuestionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query filter
	QuestionId int64 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	// Update
	Question      *string  `protobuf:"bytes,2,opt,name=question,proto3,oneof" json:"question,omitempty"`
	Answers       []string `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	Score         *int32   `protobuf:"varint,4,opt,name=score,proto3,oneof" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupJoinQuestionRequest) Reset() {
	*x = UpdateGroupJoinQuestionRequest{}
	mi := &file_request_group_enrollment_update_group_join_question_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupJoinQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupJoinQuestionRequest) ProtoMessage() {}

func (x *UpdateGroupJoinQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_group_enrollment_update_group_join_question_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupJoinQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupJoinQuestionRequest) Descriptor() ([]byte, []int) {
	return file_request_group_enrollment_update_group_join_question_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateGroupJoinQuestionRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UpdateGroupJoinQuestionRequest) GetQuestion() string {
	if x != nil && x.Question != nil {
		return *x.Question
	}
	return ""
}

func (x *UpdateGroupJoinQuestionRequest) GetAnswers() []string {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *UpdateGroupJoinQuestionRequest) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

var File_request_group_enrollment_update_group_join_question_request_proto protoreflect.FileDescriptor

const file_request_group_enrollment_update_group_join_question_request_proto_rawDesc = "" +
	"\n" +
	"Arequest/group/enrollment/update_group_join_question_request.proto\x12\x0eim.turms.proto\"\xae\x01\n" +
	"\x1eUpdateGroupJoinQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x1f\n" +
	"\bquestion\x18\x02 \x01(\tH\x00R\bquestion\x88\x01\x01\x12\x18\n" +
	"\aanswers\x18\x03 \x03(\tR\aanswers\x12\x19\n" +
	"\x05score\x18\x04 \x01(\x05H\x01R\x05score\x88\x01\x01B\v\n" +
	"\t_questionB\b\n" +
	"\x06_scoreBf\n" +
	"Aim.turms.server.common.access.client.dto.request.group.enrollmentP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_group_enrollment_update_group_join_question_request_proto_rawDescOnce sync.Once
	file_request_group_enrollment_update_group_join_question_request_proto_rawDescData []byte
)

func file_request_group_enrollment_update_group_join_question_request_proto_rawDescGZIP() []byte {
	file_request_group_enrollment_update_group_join_question_request_proto_rawDescOnce.Do(func() {
		file_request_group_enrollment_update_group_join_question_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_group_enrollment_update_group_join_question_request_proto_rawDesc), len(file_request_group_enrollment_update_group_join_question_request_proto_rawDesc)))
	})
	return file_request_group_enrollment_update_group_join_question_request_proto_rawDescData
}

var file_request_group_enrollment_update_group_join_question_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_group_enrollment_update_group_join_question_request_proto_goTypes = []any{
	(*UpdateGroupJoinQuestionRequest)(nil), // 0: im.turms.proto.UpdateGroupJoinQuestionRequest
}
var file_request_group_enrollment_update_group_join_question_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_group_enrollment_update_group_join_question_request_proto_init() }
func file_request_group_enrollment_update_group_join_question_request_proto_init() {
	if File_request_group_enrollment_update_group_join_question_request_proto != nil {
		return
	}
	file_request_group_enrollment_update_group_join_question_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_group_enrollment_update_group_join_question_request_proto_rawDesc), len(file_request_group_enrollment_update_group_join_question_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_group_enrollment_update_group_join_question_request_proto_goTypes,
		DependencyIndexes: file_request_group_enrollment_update_group_join_question_request_proto_depIdxs,
		MessageInfos:      file_request_group_enrollment_update_group_join_question_request_proto_msgTypes,
	}.Build()
	File_request_group_enrollment_update_group_join_question_request_proto = out.File
	file_request_group_enrollment_update_group_join_question_request_proto_goTypes = nil
	file_request_group_enrollment_update_group_join_question_request_proto_depIdxs = nil
}
