// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: request/conference/update_meeting_invitation_request.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMeetingInvitationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query filter
	MeetingId int64   `protobuf:"varint,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Password  *string `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	// Update
	ResponseAction ResponseAction `protobuf:"varint,5,opt,name=response_action,json=responseAction,proto3,enum=im.turms.proto.ResponseAction" json:"response_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateMeetingInvitationRequest) Reset() {
	*x = UpdateMeetingInvitationRequest{}
	mi := &file_request_conference_update_meeting_invitation_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMeetingInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMeetingInvitationRequest) ProtoMessage() {}

func (x *UpdateMeetingInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_conference_update_meeting_invitation_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMeetingInvitationRequest.ProtoReflect.Descriptor instead.
func (*UpdateMeetingInvitationRequest) Descriptor() ([]byte, []int) {
	return file_request_conference_update_meeting_invitation_request_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMeetingInvitationRequest) GetMeetingId() int64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

func (x *UpdateMeetingInvitationRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UpdateMeetingInvitationRequest) GetResponseAction() ResponseAction {
	if x != nil {
		return x.ResponseAction
	}
	return ResponseAction_ACCEPT
}

var File_request_conference_update_meeting_invitation_request_proto protoreflect.FileDescriptor

const file_request_conference_update_meeting_invitation_request_proto_rawDesc = "" +
	"\n" +
	":request/conference/update_meeting_invitation_request.proto\x12\x0eim.turms.proto\x1a\x1econstant/response_action.proto\"\xb6\x01\n" +
	"\x1eUpdateMeetingInvitationRequest\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\x03R\tmeetingId\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01\x12G\n" +
	"\x0fresponse_action\x18\x05 \x01(\x0e2\x1e.im.turms.proto.ResponseActionR\x0eresponseActionB\v\n" +
	"\t_passwordB`\n" +
	";im.turms.server.common.access.client.dto.request.conferenceP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_request_conference_update_meeting_invitation_request_proto_rawDescOnce sync.Once
	file_request_conference_update_meeting_invitation_request_proto_rawDescData []byte
)

func file_request_conference_update_meeting_invitation_request_proto_rawDescGZIP() []byte {
	file_request_conference_update_meeting_invitation_request_proto_rawDescOnce.Do(func() {
		file_request_conference_update_meeting_invitation_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_conference_update_meeting_invitation_request_proto_rawDesc), len(file_request_conference_update_meeting_invitation_request_proto_rawDesc)))
	})
	return file_request_conference_update_meeting_invitation_request_proto_rawDescData
}

var file_request_conference_update_meeting_invitation_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_conference_update_meeting_invitation_request_proto_goTypes = []any{
	(*UpdateMeetingInvitationRequest)(nil), // 0: im.turms.proto.UpdateMeetingInvitationRequest
	(ResponseAction)(0),                    // 1: im.turms.proto.ResponseAction
}
var file_request_conference_update_meeting_invitation_request_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.UpdateMeetingInvitationRequest.response_action:type_name -> im.turms.proto.ResponseAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_conference_update_meeting_invitation_request_proto_init() }
func file_request_conference_update_meeting_invitation_request_proto_init() {
	if File_request_conference_update_meeting_invitation_request_proto != nil {
		return
	}
	file_constant_response_action_proto_init()
	file_request_conference_update_meeting_invitation_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_conference_update_meeting_invitation_request_proto_rawDesc), len(file_request_conference_update_meeting_invitation_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_conference_update_meeting_invitation_request_proto_goTypes,
		DependencyIndexes: file_request_conference_update_meeting_invitation_request_proto_depIdxs,
		MessageInfos:      file_request_conference_update_meeting_invitation_request_proto_msgTypes,
	}.Build()
	File_request_conference_update_meeting_invitation_request_proto = out.File
	file_request_conference_update_meeting_invitation_request_proto_goTypes = nil
	file_request_conference_update_meeting_invitation_request_proto_depIdxs = nil
}
