// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/user/user_online_status.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOnlineStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserStatus       UserStatus             `protobuf:"varint,2,opt,name=user_status,json=userStatus,proto3,enum=im.turms.proto.UserStatus" json:"user_status,omitempty"`
	UsingDeviceTypes []DeviceType           `protobuf:"varint,3,rep,packed,name=using_device_types,json=usingDeviceTypes,proto3,enum=im.turms.proto.DeviceType" json:"using_device_types,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserOnlineStatus) Reset() {
	*x = UserOnlineStatus{}
	mi := &file_model_user_user_online_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOnlineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineStatus) ProtoMessage() {}

func (x *UserOnlineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_user_online_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineStatus.ProtoReflect.Descriptor instead.
func (*UserOnlineStatus) Descriptor() ([]byte, []int) {
	return file_model_user_user_online_status_proto_rawDescGZIP(), []int{0}
}

func (x *UserOnlineStatus) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserOnlineStatus) GetUserStatus() UserStatus {
	if x != nil {
		return x.UserStatus
	}
	return UserStatus_AVAILABLE
}

func (x *UserOnlineStatus) GetUsingDeviceTypes() []DeviceType {
	if x != nil {
		return x.UsingDeviceTypes
	}
	return nil
}

var File_model_user_user_online_status_proto protoreflect.FileDescriptor

const file_model_user_user_online_status_proto_rawDesc = "" +
	"\n" +
	"#model/user/user_online_status.proto\x12\x0eim.turms.proto\x1a\x1aconstant/user_status.proto\x1a\x1aconstant/device_type.proto\"\xb2\x01\n" +
	"\x10UserOnlineStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12;\n" +
	"\vuser_status\x18\x02 \x01(\x0e2\x1a.im.turms.proto.UserStatusR\n" +
	"userStatus\x12H\n" +
	"\x12using_device_types\x18\x03 \x03(\x0e2\x1a.im.turms.proto.DeviceTypeR\x10usingDeviceTypesBX\n" +
	"3im.turms.server.common.access.client.dto.model.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_user_user_online_status_proto_rawDescOnce sync.Once
	file_model_user_user_online_status_proto_rawDescData []byte
)

func file_model_user_user_online_status_proto_rawDescGZIP() []byte {
	file_model_user_user_online_status_proto_rawDescOnce.Do(func() {
		file_model_user_user_online_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_user_user_online_status_proto_rawDesc), len(file_model_user_user_online_status_proto_rawDesc)))
	})
	return file_model_user_user_online_status_proto_rawDescData
}

var file_model_user_user_online_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_user_user_online_status_proto_goTypes = []any{
	(*UserOnlineStatus)(nil), // 0: im.turms.proto.UserOnlineStatus
	(UserStatus)(0),          // 1: im.turms.proto.UserStatus
	(DeviceType)(0),          // 2: im.turms.proto.DeviceType
}
var file_model_user_user_online_status_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.UserOnlineStatus.user_status:type_name -> im.turms.proto.UserStatus
	2, // 1: im.turms.proto.UserOnlineStatus.using_device_types:type_name -> im.turms.proto.DeviceType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_user_user_online_status_proto_init() }
func file_model_user_user_online_status_proto_init() {
	if File_model_user_user_online_status_proto != nil {
		return
	}
	file_constant_user_status_proto_init()
	file_constant_device_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_user_user_online_status_proto_rawDesc), len(file_model_user_user_online_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_user_user_online_status_proto_goTypes,
		DependencyIndexes: file_model_user_user_online_status_proto_depIdxs,
		MessageInfos:      file_model_user_user_online_status_proto_msgTypes,
	}.Build()
	File_model_user_user_online_status_proto = out.File
	file_model_user_user_online_status_proto_goTypes = nil
	file_model_user_user_online_status_proto_depIdxs = nil
}
