// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: constant/user_status.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_AVAILABLE      UserStatus = 0
	UserStatus_OFFLINE        UserStatus = 1
	UserStatus_INVISIBLE      UserStatus = 2
	UserStatus_BUSY           UserStatus = 3
	UserStatus_DO_NOT_DISTURB UserStatus = 4
	UserStatus_AWAY           UserStatus = 5
	UserStatus_BE_RIGHT_BACK  UserStatus = 6
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "AVAILABLE",
		1: "OFFLINE",
		2: "INVISIBLE",
		3: "BUSY",
		4: "DO_NOT_DISTURB",
		5: "AWAY",
		6: "BE_RIGHT_BACK",
	}
	UserStatus_value = map[string]int32{
		"AVAILABLE":      0,
		"OFFLINE":        1,
		"INVISIBLE":      2,
		"BUSY":           3,
		"DO_NOT_DISTURB": 4,
		"AWAY":           5,
		"BE_RIGHT_BACK":  6,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_constant_user_status_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_constant_user_status_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_constant_user_status_proto_rawDescGZIP(), []int{0}
}

var File_constant_user_status_proto protoreflect.FileDescriptor

const file_constant_user_status_proto_rawDesc = "" +
	"\n" +
	"\x1aconstant/user_status.proto\x12\x0eim.turms.proto*r\n" +
	"\n" +
	"UserStatus\x12\r\n" +
	"\tAVAILABLE\x10\x00\x12\v\n" +
	"\aOFFLINE\x10\x01\x12\r\n" +
	"\tINVISIBLE\x10\x02\x12\b\n" +
	"\x04BUSY\x10\x03\x12\x12\n" +
	"\x0eDO_NOT_DISTURB\x10\x04\x12\b\n" +
	"\x04AWAY\x10\x05\x12\x11\n" +
	"\rBE_RIGHT_BACK\x10\x06BV\n" +
	"1im.turms.server.common.access.client.dto.constantP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_constant_user_status_proto_rawDescOnce sync.Once
	file_constant_user_status_proto_rawDescData []byte
)

func file_constant_user_status_proto_rawDescGZIP() []byte {
	file_constant_user_status_proto_rawDescOnce.Do(func() {
		file_constant_user_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constant_user_status_proto_rawDesc), len(file_constant_user_status_proto_rawDesc)))
	})
	return file_constant_user_status_proto_rawDescData
}

var file_constant_user_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constant_user_status_proto_goTypes = []any{
	(UserStatus)(0), // 0: im.turms.proto.UserStatus
}
var file_constant_user_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constant_user_status_proto_init() }
func file_constant_user_status_proto_init() {
	if File_constant_user_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constant_user_status_proto_rawDesc), len(file_constant_user_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constant_user_status_proto_goTypes,
		DependencyIndexes: file_constant_user_status_proto_depIdxs,
		EnumInfos:         file_constant_user_status_proto_enumTypes,
	}.Build()
	File_constant_user_status_proto = out.File
	file_constant_user_status_proto_goTypes = nil
	file_constant_user_status_proto_depIdxs = nil
}
