// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/user/user_infos_with_version.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfosWithVersion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserInfos       []*UserInfo            `protobuf:"bytes,1,rep,name=user_infos,json=userInfos,proto3" json:"user_infos,omitempty"`
	LastUpdatedDate *int64                 `protobuf:"varint,2,opt,name=last_updated_date,json=lastUpdatedDate,proto3,oneof" json:"last_updated_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserInfosWithVersion) Reset() {
	*x = UserInfosWithVersion{}
	mi := &file_model_user_user_infos_with_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfosWithVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfosWithVersion) ProtoMessage() {}

func (x *UserInfosWithVersion) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_user_infos_with_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfosWithVersion.ProtoReflect.Descriptor instead.
func (*UserInfosWithVersion) Descriptor() ([]byte, []int) {
	return file_model_user_user_infos_with_version_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfosWithVersion) GetUserInfos() []*UserInfo {
	if x != nil {
		return x.UserInfos
	}
	return nil
}

func (x *UserInfosWithVersion) GetLastUpdatedDate() int64 {
	if x != nil && x.LastUpdatedDate != nil {
		return *x.LastUpdatedDate
	}
	return 0
}

var File_model_user_user_infos_with_version_proto protoreflect.FileDescriptor

const file_model_user_user_infos_with_version_proto_rawDesc = "" +
	"\n" +
	"(model/user/user_infos_with_version.proto\x12\x0eim.turms.proto\x1a\x1amodel/user/user_info.proto\"\x96\x01\n" +
	"\x14UserInfosWithVersion\x127\n" +
	"\n" +
	"user_infos\x18\x01 \x03(\v2\x18.im.turms.proto.UserInfoR\tuserInfos\x12/\n" +
	"\x11last_updated_date\x18\x02 \x01(\x03H\x00R\x0flastUpdatedDate\x88\x01\x01B\x14\n" +
	"\x12_last_updated_dateBX\n" +
	"3im.turms.server.common.access.client.dto.model.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_user_user_infos_with_version_proto_rawDescOnce sync.Once
	file_model_user_user_infos_with_version_proto_rawDescData []byte
)

func file_model_user_user_infos_with_version_proto_rawDescGZIP() []byte {
	file_model_user_user_infos_with_version_proto_rawDescOnce.Do(func() {
		file_model_user_user_infos_with_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_user_user_infos_with_version_proto_rawDesc), len(file_model_user_user_infos_with_version_proto_rawDesc)))
	})
	return file_model_user_user_infos_with_version_proto_rawDescData
}

var file_model_user_user_infos_with_version_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_user_user_infos_with_version_proto_goTypes = []any{
	(*UserInfosWithVersion)(nil), // 0: im.turms.proto.UserInfosWithVersion
	(*UserInfo)(nil),             // 1: im.turms.proto.UserInfo
}
var file_model_user_user_infos_with_version_proto_depIdxs = []int32{
	1, // 0: im.turms.proto.UserInfosWithVersion.user_infos:type_name -> im.turms.proto.UserInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_model_user_user_infos_with_version_proto_init() }
func file_model_user_user_infos_with_version_proto_init() {
	if File_model_user_user_infos_with_version_proto != nil {
		return
	}
	file_model_user_user_info_proto_init()
	file_model_user_user_infos_with_version_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_user_user_infos_with_version_proto_rawDesc), len(file_model_user_user_infos_with_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_user_user_infos_with_version_proto_goTypes,
		DependencyIndexes: file_model_user_user_infos_with_version_proto_depIdxs,
		MessageInfos:      file_model_user_user_infos_with_version_proto_msgTypes,
	}.Build()
	File_model_user_user_infos_with_version_proto = out.File
	file_model_user_user_infos_with_version_proto_goTypes = nil
	file_model_user_user_infos_with_version_proto_depIdxs = nil
}
