// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: model/user/user_relationship_group.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRelationshipGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationshipGroup) Reset() {
	*x = UserRelationshipGroup{}
	mi := &file_model_user_user_relationship_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationshipGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationshipGroup) ProtoMessage() {}

func (x *UserRelationshipGroup) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_user_relationship_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationshipGroup.ProtoReflect.Descriptor instead.
func (*UserRelationshipGroup) Descriptor() ([]byte, []int) {
	return file_model_user_user_relationship_group_proto_rawDescGZIP(), []int{0}
}

func (x *UserRelationshipGroup) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UserRelationshipGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_model_user_user_relationship_group_proto protoreflect.FileDescriptor

const file_model_user_user_relationship_group_proto_rawDesc = "" +
	"\n" +
	"(model/user/user_relationship_group.proto\x12\x0eim.turms.proto\"A\n" +
	"\x15UserRelationshipGroup\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBX\n" +
	"3im.turms.server.common.access.client.dto.model.userP\x01Z\x1cim.turms/server/pkg/protocol\xba\x02\x00b\x06proto3"

var (
	file_model_user_user_relationship_group_proto_rawDescOnce sync.Once
	file_model_user_user_relationship_group_proto_rawDescData []byte
)

func file_model_user_user_relationship_group_proto_rawDescGZIP() []byte {
	file_model_user_user_relationship_group_proto_rawDescOnce.Do(func() {
		file_model_user_user_relationship_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_user_user_relationship_group_proto_rawDesc), len(file_model_user_user_relationship_group_proto_rawDesc)))
	})
	return file_model_user_user_relationship_group_proto_rawDescData
}

var file_model_user_user_relationship_group_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_model_user_user_relationship_group_proto_goTypes = []any{
	(*UserRelationshipGroup)(nil), // 0: im.turms.proto.UserRelationshipGroup
}
var file_model_user_user_relationship_group_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_user_user_relationship_group_proto_init() }
func file_model_user_user_relationship_group_proto_init() {
	if File_model_user_user_relationship_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_user_user_relationship_group_proto_rawDesc), len(file_model_user_user_relationship_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_user_user_relationship_group_proto_goTypes,
		DependencyIndexes: file_model_user_user_relationship_group_proto_depIdxs,
		MessageInfos:      file_model_user_user_relationship_group_proto_msgTypes,
	}.Build()
	File_model_user_user_relationship_group_proto = out.File
	file_model_user_user_relationship_group_proto_goTypes = nil
	file_model_user_user_relationship_group_proto_depIdxs = nil
}
